"""Response schemas for insight endpoints.

This module is automatically @generated from the Meraki API specification.
Do not edit this file manually.
"""

from __future__ import annotations

from datetime import datetime

from pydantic import Field, RootModel

from meraki_client.schemas._base import _BaseSchema


class GetNetworkInsightApplicationHealthByTimeResponse(
    RootModel[list["GetNetworkInsightApplicationHealthByTimeResponseItem"]]
):
    """Response for getNetworkInsightApplicationHealthByTime operation."""


class GetNetworkInsightApplicationHealthByTimeResponseItem(_BaseSchema):
    """Schema for GetNetworkInsightApplicationHealthByTimeResponseItem."""

    start_ts: datetime | None = Field(
        default=None, validation_alias="startTs", serialization_alias="startTs"
    )
    end_ts: datetime | None = Field(
        default=None, validation_alias="endTs", serialization_alias="endTs"
    )
    wan_goodput: int | None = Field(
        default=None, validation_alias="wanGoodput", serialization_alias="wanGoodput"
    )
    lan_goodput: int | None = Field(
        default=None, validation_alias="lanGoodput", serialization_alias="lanGoodput"
    )
    wan_latency_ms: float | None = Field(
        default=None, validation_alias="wanLatencyMs", serialization_alias="wanLatencyMs"
    )
    lan_latency_ms: float | None = Field(
        default=None, validation_alias="lanLatencyMs", serialization_alias="lanLatencyMs"
    )
    wan_loss_percent: float | None = Field(
        default=None, validation_alias="wanLossPercent", serialization_alias="wanLossPercent"
    )
    lan_loss_percent: float | None = Field(
        default=None, validation_alias="lanLossPercent", serialization_alias="lanLossPercent"
    )
    response_duration: int | None = Field(
        default=None, validation_alias="responseDuration", serialization_alias="responseDuration"
    )
    sent: int | None = None
    recv: int | None = None
    num_clients: int | None = Field(
        default=None, validation_alias="numClients", serialization_alias="numClients"
    )


class GetOrganizationInsightApplicationsResponse(
    RootModel[list["GetOrganizationInsightApplicationsResponseItem"]]
):
    """Response for getOrganizationInsightApplications operation."""


class GetOrganizationInsightApplicationsResponseItem(_BaseSchema):
    """Schema for GetOrganizationInsightApplicationsResponseItem."""

    application_id: str | None = Field(
        default=None, validation_alias="applicationId", serialization_alias="applicationId"
    )
    name: str | None = None
    thresholds: InsightThresholds | None = None


class GetOrganizationInsightMonitoredMediaServersResponse(
    RootModel[list["OrganizationInsightMonitoredMediaServerResponse"]]
):
    """Response for getOrganizationInsightMonitoredMediaServers operation."""


class InsightByNetworkItem(_BaseSchema):
    """Schema for InsightByNetworkItem."""

    network_id: str | None = Field(
        default=None, validation_alias="networkId", serialization_alias="networkId"
    )
    goodput: int | None = None
    response_duration: int | None = Field(
        default=None, validation_alias="responseDuration", serialization_alias="responseDuration"
    )


class InsightThresholds(_BaseSchema):
    """Thresholds defined by a user or Meraki models for each application."""

    type_: str | None = Field(default=None, validation_alias="type", serialization_alias="type")
    by_network: list[InsightByNetworkItem] = Field(
        default_factory=list, validation_alias="byNetwork", serialization_alias="byNetwork"
    )


class OrganizationInsightMonitoredMediaServerResponse(_BaseSchema):
    """Schema for OrganizationInsightMonitoredMediaServerResponse."""

    id: str | None = None
    name: str | None = None
    address: str | None = None
    best_effort_monitoring_enabled: bool | None = Field(
        default=None,
        validation_alias="bestEffortMonitoringEnabled",
        serialization_alias="bestEffortMonitoringEnabled",
    )
