"""Response schemas for spaces endpoints.

This module is automatically @generated from the Meraki API specification.
Do not edit this file manually.
"""

from __future__ import annotations

from typing import Any

from pydantic import Field, field_validator

from meraki_client.schemas._base import _BaseSchema


class GetOrganizationSpacesIntegrateStatusResponse(_BaseSchema):
    """Response for getOrganizationSpacesIntegrateStatus operation."""

    status: bool | None = None
    states: list[str] = Field(default_factory=list)
    email: str | None = None
    account_name: str | None = Field(
        default=None, validation_alias="accountName", serialization_alias="accountName"
    )
    account_type: str | None = Field(
        default=None, validation_alias="accountType", serialization_alias="accountType"
    )

    @field_validator("states", mode="before")
    @classmethod
    def coerce_null_lists(cls, value: Any) -> Any:
        """Convert null array values from the API to empty lists."""
        return [] if value is None else value


class RemoveOrganizationSpacesIntegrationResponse(_BaseSchema):
    """Response for removeOrganizationSpacesIntegration operation."""

    status: bool | None = None
    message: str | None = None
