"""Response schemas for camera endpoints.

This module is automatically @generated from the Meraki API specification.
Do not edit this file manually.
"""

from typing import Any

from pydantic import Field, RootModel

from meraki_client.schemas._base import _BaseSchema


class GetDeviceCameraAnalyticsLiveResponseZonesZoneId(_BaseSchema):
    """The zone state, dynamic."""

    person: int | None = None


class GetDeviceCameraAnalyticsOverviewResponseItem(_BaseSchema):
    """Schema for GetDeviceCameraAnalyticsOverviewResponseItem."""

    start_ts: str | None = Field(default=None, alias="startTs")
    end_ts: str | None = Field(default=None, alias="endTs")
    zone_id: int | None = Field(default=None, alias="zoneId")
    entrances: int | None = None
    average_count: float | None = Field(default=None, alias="averageCount")


class GetDeviceCameraAnalyticsRecentResponseItem(_BaseSchema):
    """Schema for GetDeviceCameraAnalyticsRecentResponseItem."""

    start_ts: str | None = Field(default=None, alias="startTs")
    end_ts: str | None = Field(default=None, alias="endTs")
    zone_id: int | None = Field(default=None, alias="zoneId")
    entrances: int | None = None
    average_count: float | None = Field(default=None, alias="averageCount")


class GetDeviceCameraAnalyticsZonesResponseItemRegionOfInterest(_BaseSchema):
    """The region of interest."""

    x0: str | None = None
    y0: str | None = None
    x1: str | None = None
    y1: str | None = None


class GetDeviceCameraAnalyticsZoneHistoryResponseItem(_BaseSchema):
    """Schema for GetDeviceCameraAnalyticsZoneHistoryResponseItem."""

    start_ts: str | None = Field(default=None, alias="startTs")
    end_ts: str | None = Field(default=None, alias="endTs")
    entrances: int | None = None
    average_count: float | None = Field(default=None, alias="averageCount")


class GetDeviceCameraCustomAnalyticsResponseParametersItem(_BaseSchema):
    """Schema for GetDeviceCameraCustomAnalyticsResponseParametersItem."""

    name: str | None = None
    value: float | None = None


class UpdateDeviceCameraCustomAnalyticsResponseParametersItem(_BaseSchema):
    """Schema for UpdateDeviceCameraCustomAnalyticsResponseParametersItem."""

    name: str | None = None
    value: float | None = None


class GenerateDeviceCameraSnapshotResponse(_BaseSchema):
    """Generate a snapshot of what the camera sees at the specified time and return a link to that
    image.
    """

    url: str | None = None
    expiry: str | None = None


class GetDeviceCameraQualityAndRetentionResponse(_BaseSchema):
    """Returns quality and retention settings for the given camera."""


class UpdateDeviceCameraQualityAndRetentionResponse(_BaseSchema):
    """Update quality and retention settings for the given camera."""


class GetDeviceCameraSenseResponse(_BaseSchema):
    """Returns sense settings for a given camera."""


class UpdateDeviceCameraSenseResponse(_BaseSchema):
    """Update sense settings for the given camera."""


class GetDeviceCameraSenseObjectDetectionModelsResponseItem(_BaseSchema):
    """Schema for GetDeviceCameraSenseObjectDetectionModelsResponseItem."""


class GetDeviceCameraVideoSettingsResponse(_BaseSchema):
    """Returns video settings for the given camera."""

    external_rtsp_enabled: bool | None = Field(default=None, alias="externalRtspEnabled")
    rtsp_url: str | None = Field(default=None, alias="rtspUrl")


class UpdateDeviceCameraVideoSettingsResponse(_BaseSchema):
    """Update video settings for the given camera."""

    external_rtsp_enabled: bool | None = Field(default=None, alias="externalRtspEnabled")
    rtsp_url: str | None = Field(default=None, alias="rtspUrl")


class GetDeviceCameraVideoLinkResponse(_BaseSchema):
    """Returns video link to the specified camera. If a timestamp is supplied, it links to that
    timestamp.
    """


class GetDeviceCameraWirelessProfilesResponse(_BaseSchema):
    """Returns wireless profile assigned to the given camera."""


class UpdateDeviceCameraWirelessProfilesResponse(_BaseSchema):
    """Assign wireless profiles to the given camera. Incremental updates are not supported, all
    profile assignment need to be supplied at once.
    """


class GetNetworkCameraQualityRetentionProfilesResponseItemSmartRetention(_BaseSchema):
    """Smart retention settings."""

    enabled: bool | None = None


class CreateNetworkCameraQualityRetentionProfileResponseSmartRetention(_BaseSchema):
    """Smart retention settings."""

    enabled: bool | None = None


class GetNetworkCameraQualityRetentionProfileResponseSmartRetention(_BaseSchema):
    """Smart retention settings."""

    enabled: bool | None = None


class UpdateNetworkCameraQualityRetentionProfileResponseSmartRetention(_BaseSchema):
    """Smart retention settings."""

    enabled: bool | None = None


class GetNetworkCameraSchedulesResponseItem(_BaseSchema):
    """Schema for GetNetworkCameraSchedulesResponseItem."""

    id_: str | None = Field(default=None, alias="id")
    name: str | None = None


class GetNetworkCameraWirelessProfilesResponseItemSsid(_BaseSchema):
    """The details of the SSID config."""

    name: str | None = None
    auth_mode: str | None = Field(default=None, alias="authMode")
    encryption_mode: str | None = Field(default=None, alias="encryptionMode")
    psk: str | None = None


class GetNetworkCameraWirelessProfilesResponseItemIdentity(_BaseSchema):
    """The identity of the wireless profile. Required for creating wireless profiles in
    8021x-radius auth mode.
    """

    username: str | None = None
    password: str | None = None


class CreateNetworkCameraWirelessProfileResponseSsid(_BaseSchema):
    """The details of the SSID config."""

    name: str | None = None
    auth_mode: str | None = Field(default=None, alias="authMode")
    encryption_mode: str | None = Field(default=None, alias="encryptionMode")
    psk: str | None = None


class CreateNetworkCameraWirelessProfileResponseIdentity(_BaseSchema):
    """The identity of the wireless profile. Required for creating wireless profiles in
    8021x-radius auth mode.
    """

    username: str | None = None
    password: str | None = None


class GetNetworkCameraWirelessProfileResponseSsid(_BaseSchema):
    """The details of the SSID config."""

    name: str | None = None
    auth_mode: str | None = Field(default=None, alias="authMode")
    encryption_mode: str | None = Field(default=None, alias="encryptionMode")
    psk: str | None = None


class GetNetworkCameraWirelessProfileResponseIdentity(_BaseSchema):
    """The identity of the wireless profile. Required for creating wireless profiles in
    8021x-radius auth mode.
    """

    username: str | None = None
    password: str | None = None


class UpdateNetworkCameraWirelessProfileResponseSsid(_BaseSchema):
    """The details of the SSID config."""

    name: str | None = None
    auth_mode: str | None = Field(default=None, alias="authMode")
    encryption_mode: str | None = Field(default=None, alias="encryptionMode")
    psk: str | None = None


class UpdateNetworkCameraWirelessProfileResponseIdentity(_BaseSchema):
    """The identity of the wireless profile. Required for creating wireless profiles in
    8021x-radius auth mode.
    """

    username: str | None = None
    password: str | None = None


class GetOrganizationCameraBoundariesAreasByDeviceResponseItemBoundariesVerticesItem(_BaseSchema):
    """Schema for GetOrganizationCameraBoundariesAreasByDeviceResponseItemBoundariesVerticesItem."""

    x: float | None = None
    y: float | None = None


class GetOrganizationCameraBoundariesLinesByDeviceResponseItemBoundariesVerticesItem(_BaseSchema):
    """Schema for GetOrganizationCameraBoundariesLinesByDeviceResponseItemBoundariesVerticesItem."""

    x: float | None = None
    y: float | None = None


class GetOrganizationCameraBoundariesLinesByDeviceResponseItemBoundariesDirectionVertex(
    _BaseSchema
):
    """The line boundary crossing direction vertex."""

    x: float | None = None
    y: float | None = None


class GetOrganizationCameraCustomAnalyticsArtifactsResponseItemStatus(_BaseSchema):
    """Custom analytics artifact status."""

    type_: str | None = Field(default=None, alias="type")
    message: str | None = None


class CreateOrganizationCameraCustomAnalyticsArtifactResponseStatus(_BaseSchema):
    """Custom analytics artifact status."""

    type_: str | None = Field(default=None, alias="type")
    message: str | None = None


class GetOrganizationCameraCustomAnalyticsArtifactResponseStatus(_BaseSchema):
    """Custom analytics artifact status."""

    type_: str | None = Field(default=None, alias="type")
    message: str | None = None


class GetOrganizationCameraDetectionsHistoryByBoundaryByIntervalResponseItemResults(_BaseSchema):
    """The analytics data."""

    start_time: str | None = Field(default=None, alias="startTime")
    end_time: str | None = Field(default=None, alias="endTime")
    object_type: str | None = Field(default=None, alias="objectType")
    in_: int | None = Field(default=None, alias="in")
    out: int | None = None


class GetOrganizationCameraOnboardingStatusesResponseItem(_BaseSchema):
    """Schema for GetOrganizationCameraOnboardingStatusesResponseItem."""


class UpdateOrganizationCameraOnboardingStatusesResponse(_BaseSchema):
    """Notify that credential handoff to camera has completed."""


class GetOrganizationCameraPermissionsResponseItem(_BaseSchema):
    """Schema for GetOrganizationCameraPermissionsResponseItem."""

    id_: str | None = Field(default=None, alias="id")
    name: str | None = None
    level: str | None = None


class GetOrganizationCameraPermissionResponse(_BaseSchema):
    """Retrieve a single permission scope."""

    id_: str | None = Field(default=None, alias="id")
    name: str | None = None
    level: str | None = None


class GetOrganizationCameraRolesResponseItemAppliedOnDevicesItem(_BaseSchema):
    """Schema for GetOrganizationCameraRolesResponseItemAppliedOnDevicesItem."""

    tag: str | None = None
    id_: str | None = Field(default=None, alias="id")
    permission_scope_id: str | None = Field(default=None, alias="permissionScopeId")
    permission_scope: str | None = Field(default=None, alias="permissionScope")
    permission_level: str | None = Field(default=None, alias="permissionLevel")


class GetOrganizationCameraRolesResponseItemAppliedOnNetworksItem(_BaseSchema):
    """Schema for GetOrganizationCameraRolesResponseItemAppliedOnNetworksItem."""

    tag: str | None = None
    id_: str | None = Field(default=None, alias="id")
    permission_scope_id: str | None = Field(default=None, alias="permissionScopeId")
    permission_scope: str | None = Field(default=None, alias="permissionScope")
    permission_level: str | None = Field(default=None, alias="permissionLevel")


class GetOrganizationCameraRolesResponseItemAppliedOrgWideItem(_BaseSchema):
    """Schema for GetOrganizationCameraRolesResponseItemAppliedOrgWideItem."""

    tag: str | None = None
    permission_scope_id: str | None = Field(default=None, alias="permissionScopeId")
    permission_scope: str | None = Field(default=None, alias="permissionScope")
    permission_level: str | None = Field(default=None, alias="permissionLevel")


class CreateOrganizationCameraRoleResponseAppliedOnDevicesItem(_BaseSchema):
    """Schema for CreateOrganizationCameraRoleResponseAppliedOnDevicesItem."""

    tag: str | None = None
    id_: str | None = Field(default=None, alias="id")
    permission_scope_id: str | None = Field(default=None, alias="permissionScopeId")
    permission_scope: str | None = Field(default=None, alias="permissionScope")
    permission_level: str | None = Field(default=None, alias="permissionLevel")


class CreateOrganizationCameraRoleResponseAppliedOnNetworksItem(_BaseSchema):
    """Schema for CreateOrganizationCameraRoleResponseAppliedOnNetworksItem."""

    tag: str | None = None
    id_: str | None = Field(default=None, alias="id")
    permission_scope_id: str | None = Field(default=None, alias="permissionScopeId")
    permission_scope: str | None = Field(default=None, alias="permissionScope")
    permission_level: str | None = Field(default=None, alias="permissionLevel")


class CreateOrganizationCameraRoleResponseAppliedOrgWideItem(_BaseSchema):
    """Schema for CreateOrganizationCameraRoleResponseAppliedOrgWideItem."""

    tag: str | None = None
    permission_scope_id: str | None = Field(default=None, alias="permissionScopeId")
    permission_scope: str | None = Field(default=None, alias="permissionScope")
    permission_level: str | None = Field(default=None, alias="permissionLevel")


class GetOrganizationCameraRoleResponseAppliedOnDevicesItem(_BaseSchema):
    """Schema for GetOrganizationCameraRoleResponseAppliedOnDevicesItem."""

    tag: str | None = None
    id_: str | None = Field(default=None, alias="id")
    permission_scope_id: str | None = Field(default=None, alias="permissionScopeId")
    permission_scope: str | None = Field(default=None, alias="permissionScope")
    permission_level: str | None = Field(default=None, alias="permissionLevel")


class GetOrganizationCameraRoleResponseAppliedOnNetworksItem(_BaseSchema):
    """Schema for GetOrganizationCameraRoleResponseAppliedOnNetworksItem."""

    tag: str | None = None
    id_: str | None = Field(default=None, alias="id")
    permission_scope_id: str | None = Field(default=None, alias="permissionScopeId")
    permission_scope: str | None = Field(default=None, alias="permissionScope")
    permission_level: str | None = Field(default=None, alias="permissionLevel")


class GetOrganizationCameraRoleResponseAppliedOrgWideItem(_BaseSchema):
    """Schema for GetOrganizationCameraRoleResponseAppliedOrgWideItem."""

    tag: str | None = None
    permission_scope_id: str | None = Field(default=None, alias="permissionScopeId")
    permission_scope: str | None = Field(default=None, alias="permissionScope")
    permission_level: str | None = Field(default=None, alias="permissionLevel")


class UpdateOrganizationCameraRoleResponseAppliedOnDevicesItem(_BaseSchema):
    """Schema for UpdateOrganizationCameraRoleResponseAppliedOnDevicesItem."""

    tag: str | None = None
    id_: str | None = Field(default=None, alias="id")
    permission_scope_id: str | None = Field(default=None, alias="permissionScopeId")
    permission_scope: str | None = Field(default=None, alias="permissionScope")
    permission_level: str | None = Field(default=None, alias="permissionLevel")


class UpdateOrganizationCameraRoleResponseAppliedOnNetworksItem(_BaseSchema):
    """Schema for UpdateOrganizationCameraRoleResponseAppliedOnNetworksItem."""

    tag: str | None = None
    id_: str | None = Field(default=None, alias="id")
    permission_scope_id: str | None = Field(default=None, alias="permissionScopeId")
    permission_scope: str | None = Field(default=None, alias="permissionScope")
    permission_level: str | None = Field(default=None, alias="permissionLevel")


class UpdateOrganizationCameraRoleResponseAppliedOrgWideItem(_BaseSchema):
    """Schema for UpdateOrganizationCameraRoleResponseAppliedOrgWideItem."""

    tag: str | None = None
    permission_scope_id: str | None = Field(default=None, alias="permissionScopeId")
    permission_scope: str | None = Field(default=None, alias="permissionScope")
    permission_level: str | None = Field(default=None, alias="permissionLevel")


class GetDeviceCameraAnalyticsOverviewResponse(
    RootModel[list[GetDeviceCameraAnalyticsOverviewResponseItem]]
):
    """Returns an overview of aggregate analytics data for a timespan."""


class GetDeviceCameraAnalyticsRecentResponse(
    RootModel[list[GetDeviceCameraAnalyticsRecentResponseItem]]
):
    """Returns most recent record for analytics zones."""


class GetDeviceCameraAnalyticsZoneHistoryResponse(
    RootModel[list[GetDeviceCameraAnalyticsZoneHistoryResponseItem]]
):
    """Return historical records for analytic zones."""


class GetDeviceCameraCustomAnalyticsResponse(_BaseSchema):
    """Return custom analytics settings for a camera."""

    enabled: bool | None = None
    artifact_id: str | None = Field(default=None, alias="artifactId")
    parameters: list[GetDeviceCameraCustomAnalyticsResponseParametersItem] | None = None


class UpdateDeviceCameraCustomAnalyticsResponse(_BaseSchema):
    """Update custom analytics settings for a camera."""

    enabled: bool | None = None
    artifact_id: str | None = Field(default=None, alias="artifactId")
    parameters: list[UpdateDeviceCameraCustomAnalyticsResponseParametersItem] | None = None


class GetDeviceCameraSenseObjectDetectionModelsResponse(
    RootModel[list[GetDeviceCameraSenseObjectDetectionModelsResponseItem]]
):
    """Returns the MV Sense object detection model list for the given camera."""


class CreateNetworkCameraQualityRetentionProfileResponse(_BaseSchema):
    """Creates new quality retention profile for this network."""

    id_: str | None = Field(default=None, alias="id")
    network_id: str | None = Field(default=None, alias="networkId")
    name: str | None = None
    restricted_bandwidth_mode_enabled: bool | None = Field(
        default=None, alias="restrictedBandwidthModeEnabled"
    )
    motion_based_retention_enabled: bool | None = Field(
        default=None, alias="motionBasedRetentionEnabled"
    )
    audio_recording_enabled: bool | None = Field(default=None, alias="audioRecordingEnabled")
    cloud_archive_enabled: bool | None = Field(default=None, alias="cloudArchiveEnabled")
    max_retention_days: int | None = Field(default=None, alias="maxRetentionDays")
    schedule_id: str | None = Field(default=None, alias="scheduleId")
    motion_detector_version: int | None = Field(default=None, alias="motionDetectorVersion")
    smart_retention: CreateNetworkCameraQualityRetentionProfileResponseSmartRetention | None = (
        Field(default=None, alias="smartRetention")
    )
    video_settings: dict[str, Any] | None = Field(default=None, alias="videoSettings")


class GetNetworkCameraQualityRetentionProfileResponse(_BaseSchema):
    """Retrieve a single quality retention profile."""

    id_: str | None = Field(default=None, alias="id")
    network_id: str | None = Field(default=None, alias="networkId")
    name: str | None = None
    restricted_bandwidth_mode_enabled: bool | None = Field(
        default=None, alias="restrictedBandwidthModeEnabled"
    )
    motion_based_retention_enabled: bool | None = Field(
        default=None, alias="motionBasedRetentionEnabled"
    )
    audio_recording_enabled: bool | None = Field(default=None, alias="audioRecordingEnabled")
    cloud_archive_enabled: bool | None = Field(default=None, alias="cloudArchiveEnabled")
    max_retention_days: int | None = Field(default=None, alias="maxRetentionDays")
    schedule_id: str | None = Field(default=None, alias="scheduleId")
    motion_detector_version: int | None = Field(default=None, alias="motionDetectorVersion")
    smart_retention: GetNetworkCameraQualityRetentionProfileResponseSmartRetention | None = Field(
        default=None, alias="smartRetention"
    )
    video_settings: dict[str, Any] | None = Field(default=None, alias="videoSettings")


class UpdateNetworkCameraQualityRetentionProfileResponse(_BaseSchema):
    """Update an existing quality retention profile for this network."""

    id_: str | None = Field(default=None, alias="id")
    network_id: str | None = Field(default=None, alias="networkId")
    name: str | None = None
    restricted_bandwidth_mode_enabled: bool | None = Field(
        default=None, alias="restrictedBandwidthModeEnabled"
    )
    motion_based_retention_enabled: bool | None = Field(
        default=None, alias="motionBasedRetentionEnabled"
    )
    audio_recording_enabled: bool | None = Field(default=None, alias="audioRecordingEnabled")
    cloud_archive_enabled: bool | None = Field(default=None, alias="cloudArchiveEnabled")
    max_retention_days: int | None = Field(default=None, alias="maxRetentionDays")
    schedule_id: str | None = Field(default=None, alias="scheduleId")
    motion_detector_version: int | None = Field(default=None, alias="motionDetectorVersion")
    smart_retention: UpdateNetworkCameraQualityRetentionProfileResponseSmartRetention | None = (
        Field(default=None, alias="smartRetention")
    )
    video_settings: dict[str, Any] | None = Field(default=None, alias="videoSettings")


class GetNetworkCameraSchedulesResponse(RootModel[list[GetNetworkCameraSchedulesResponseItem]]):
    """Returns a list of all camera recording schedules."""


class CreateNetworkCameraWirelessProfileResponse(_BaseSchema):
    """Creates a new camera wireless profile for this network."""

    id_: str | None = Field(default=None, alias="id")
    name: str | None = None
    applied_device_count: int | None = Field(default=None, alias="appliedDeviceCount")
    ssid: CreateNetworkCameraWirelessProfileResponseSsid | None = None
    identity: CreateNetworkCameraWirelessProfileResponseIdentity | None = None


class GetNetworkCameraWirelessProfileResponse(_BaseSchema):
    """Retrieve a single camera wireless profile."""

    id_: str | None = Field(default=None, alias="id")
    name: str | None = None
    applied_device_count: int | None = Field(default=None, alias="appliedDeviceCount")
    ssid: GetNetworkCameraWirelessProfileResponseSsid | None = None
    identity: GetNetworkCameraWirelessProfileResponseIdentity | None = None


class UpdateNetworkCameraWirelessProfileResponse(_BaseSchema):
    """Update an existing camera wireless profile in this network."""

    id_: str | None = Field(default=None, alias="id")
    name: str | None = None
    applied_device_count: int | None = Field(default=None, alias="appliedDeviceCount")
    ssid: UpdateNetworkCameraWirelessProfileResponseSsid | None = None
    identity: UpdateNetworkCameraWirelessProfileResponseIdentity | None = None


class GetOrganizationCameraBoundariesAreasByDeviceResponseItemBoundaries(_BaseSchema):
    """Configured area boundaries of the camera."""

    id_: str | None = Field(default=None, alias="id")
    type_: str | None = Field(default=None, alias="type")
    name: str | None = None
    vertices: (
        list[GetOrganizationCameraBoundariesAreasByDeviceResponseItemBoundariesVerticesItem] | None
    ) = None


class CreateOrganizationCameraCustomAnalyticsArtifactResponse(_BaseSchema):
    """Create custom analytics artifact. Returns an artifact upload URL with expiry time. Upload
    the artifact file with a put request to the returned upload URL before its expiry.
    """

    artifact_id: str | None = Field(default=None, alias="artifactId")
    organization_id: str | None = Field(default=None, alias="organizationId")
    name: str | None = None
    status: CreateOrganizationCameraCustomAnalyticsArtifactResponseStatus | None = None
    upload_id: str | None = Field(default=None, alias="uploadId")
    upload_url: str | None = Field(default=None, alias="uploadUrl")
    upload_url_expiry: str | None = Field(default=None, alias="uploadUrlExpiry")


class GetOrganizationCameraCustomAnalyticsArtifactResponse(_BaseSchema):
    """Get Custom Analytics Artifact."""

    artifact_id: str | None = Field(default=None, alias="artifactId")
    organization_id: str | None = Field(default=None, alias="organizationId")
    name: str | None = None
    status: GetOrganizationCameraCustomAnalyticsArtifactResponseStatus | None = None


class GetOrganizationCameraOnboardingStatusesResponse(
    RootModel[list[GetOrganizationCameraOnboardingStatusesResponseItem]]
):
    """Fetch onboarding status of cameras."""


class GetOrganizationCameraPermissionsResponse(
    RootModel[list[GetOrganizationCameraPermissionsResponseItem]]
):
    """List the permissions scopes for this organization."""


class GetOrganizationCameraRolesResponseItem(_BaseSchema):
    """Schema for GetOrganizationCameraRolesResponseItem."""

    name: str | None = None
    applied_on_devices: list[GetOrganizationCameraRolesResponseItemAppliedOnDevicesItem] | None = (
        Field(default=None, alias="appliedOnDevices")
    )
    applied_on_networks: (
        list[GetOrganizationCameraRolesResponseItemAppliedOnNetworksItem] | None
    ) = Field(default=None, alias="appliedOnNetworks")
    applied_org_wide: list[GetOrganizationCameraRolesResponseItemAppliedOrgWideItem] | None = Field(
        default=None, alias="appliedOrgWide"
    )


class CreateOrganizationCameraRoleResponse(_BaseSchema):
    """Creates new role for this organization."""

    name: str | None = None
    applied_on_devices: list[CreateOrganizationCameraRoleResponseAppliedOnDevicesItem] | None = (
        Field(default=None, alias="appliedOnDevices")
    )
    applied_on_networks: list[CreateOrganizationCameraRoleResponseAppliedOnNetworksItem] | None = (
        Field(default=None, alias="appliedOnNetworks")
    )
    applied_org_wide: list[CreateOrganizationCameraRoleResponseAppliedOrgWideItem] | None = Field(
        default=None, alias="appliedOrgWide"
    )


class GetOrganizationCameraRoleResponse(_BaseSchema):
    """Retrieve a single role."""

    name: str | None = None
    applied_on_devices: list[GetOrganizationCameraRoleResponseAppliedOnDevicesItem] | None = Field(
        default=None, alias="appliedOnDevices"
    )
    applied_on_networks: list[GetOrganizationCameraRoleResponseAppliedOnNetworksItem] | None = (
        Field(default=None, alias="appliedOnNetworks")
    )
    applied_org_wide: list[GetOrganizationCameraRoleResponseAppliedOrgWideItem] | None = Field(
        default=None, alias="appliedOrgWide"
    )


class UpdateOrganizationCameraRoleResponse(_BaseSchema):
    """Update an existing role in this organization."""

    name: str | None = None
    applied_on_devices: list[UpdateOrganizationCameraRoleResponseAppliedOnDevicesItem] | None = (
        Field(default=None, alias="appliedOnDevices")
    )
    applied_on_networks: list[UpdateOrganizationCameraRoleResponseAppliedOnNetworksItem] | None = (
        Field(default=None, alias="appliedOnNetworks")
    )
    applied_org_wide: list[UpdateOrganizationCameraRoleResponseAppliedOrgWideItem] | None = Field(
        default=None, alias="appliedOrgWide"
    )


class GetOrganizationCameraRolesResponse(RootModel[list[GetOrganizationCameraRolesResponseItem]]):
    """List all the roles in this organization."""


class GetDeviceCameraAnalyticsLiveResponseZones(_BaseSchema):
    """The zones state."""

    zone_id: GetDeviceCameraAnalyticsLiveResponseZonesZoneId | None = Field(
        default=None, alias="zoneId"
    )


class GetDeviceCameraAnalyticsLiveResponse(_BaseSchema):
    """Returns live state from camera analytics zones."""

    ts: str | None = None
    zones: GetDeviceCameraAnalyticsLiveResponseZones | None = None


class GetDeviceCameraAnalyticsZonesResponseItem(_BaseSchema):
    """Schema for GetDeviceCameraAnalyticsZonesResponseItem."""

    id_: str | None = Field(default=None, alias="id")
    type_: str | None = Field(default=None, alias="type")
    label: str | None = None
    region_of_interest: GetDeviceCameraAnalyticsZonesResponseItemRegionOfInterest | None = Field(
        default=None, alias="regionOfInterest"
    )


class GetDeviceCameraAnalyticsZonesResponse(
    RootModel[list[GetDeviceCameraAnalyticsZonesResponseItem]]
):
    """Returns all configured analytic zones for this camera."""


class GetNetworkCameraQualityRetentionProfilesResponseItem(_BaseSchema):
    """Schema for GetNetworkCameraQualityRetentionProfilesResponseItem."""

    id_: str | None = Field(default=None, alias="id")
    network_id: str | None = Field(default=None, alias="networkId")
    name: str | None = None
    restricted_bandwidth_mode_enabled: bool | None = Field(
        default=None, alias="restrictedBandwidthModeEnabled"
    )
    motion_based_retention_enabled: bool | None = Field(
        default=None, alias="motionBasedRetentionEnabled"
    )
    audio_recording_enabled: bool | None = Field(default=None, alias="audioRecordingEnabled")
    cloud_archive_enabled: bool | None = Field(default=None, alias="cloudArchiveEnabled")
    max_retention_days: int | None = Field(default=None, alias="maxRetentionDays")
    schedule_id: str | None = Field(default=None, alias="scheduleId")
    motion_detector_version: int | None = Field(default=None, alias="motionDetectorVersion")
    smart_retention: GetNetworkCameraQualityRetentionProfilesResponseItemSmartRetention | None = (
        Field(default=None, alias="smartRetention")
    )
    video_settings: dict[str, Any] | None = Field(default=None, alias="videoSettings")


class GetNetworkCameraQualityRetentionProfilesResponse(
    RootModel[list[GetNetworkCameraQualityRetentionProfilesResponseItem]]
):
    """List the quality retention profiles for this network."""


class GetNetworkCameraWirelessProfilesResponseItem(_BaseSchema):
    """Schema for GetNetworkCameraWirelessProfilesResponseItem."""

    id_: str | None = Field(default=None, alias="id")
    name: str | None = None
    applied_device_count: int | None = Field(default=None, alias="appliedDeviceCount")
    ssid: GetNetworkCameraWirelessProfilesResponseItemSsid | None = None
    identity: GetNetworkCameraWirelessProfilesResponseItemIdentity | None = None


class GetNetworkCameraWirelessProfilesResponse(
    RootModel[list[GetNetworkCameraWirelessProfilesResponseItem]]
):
    """List the camera wireless profiles for this network."""


class GetOrganizationCameraBoundariesAreasByDeviceResponseItem(_BaseSchema):
    """Schema for GetOrganizationCameraBoundariesAreasByDeviceResponseItem."""

    network_id: str | None = Field(default=None, alias="networkId")
    serial: str | None = None
    boundaries: GetOrganizationCameraBoundariesAreasByDeviceResponseItemBoundaries | None = None


class GetOrganizationCameraBoundariesAreasByDeviceResponse(
    RootModel[list[GetOrganizationCameraBoundariesAreasByDeviceResponseItem]]
):
    """Returns all configured area boundaries of cameras."""


class GetOrganizationCameraBoundariesLinesByDeviceResponseItemBoundaries(_BaseSchema):
    """Configured line boundaries of the camera."""

    id_: str | None = Field(default=None, alias="id")
    type_: str | None = Field(default=None, alias="type")
    name: str | None = None
    vertices: (
        list[GetOrganizationCameraBoundariesLinesByDeviceResponseItemBoundariesVerticesItem] | None
    ) = None
    direction_vertex: (
        GetOrganizationCameraBoundariesLinesByDeviceResponseItemBoundariesDirectionVertex | None
    ) = Field(default=None, alias="directionVertex")


class GetOrganizationCameraBoundariesLinesByDeviceResponseItem(_BaseSchema):
    """Schema for GetOrganizationCameraBoundariesLinesByDeviceResponseItem."""

    network_id: str | None = Field(default=None, alias="networkId")
    serial: str | None = None
    boundaries: GetOrganizationCameraBoundariesLinesByDeviceResponseItemBoundaries | None = None


class GetOrganizationCameraBoundariesLinesByDeviceResponse(
    RootModel[list[GetOrganizationCameraBoundariesLinesByDeviceResponseItem]]
):
    """Returns all configured crossingline boundaries of cameras."""


class GetOrganizationCameraCustomAnalyticsArtifactsResponseItem(_BaseSchema):
    """Schema for GetOrganizationCameraCustomAnalyticsArtifactsResponseItem."""

    artifact_id: str | None = Field(default=None, alias="artifactId")
    organization_id: str | None = Field(default=None, alias="organizationId")
    name: str | None = None
    status: GetOrganizationCameraCustomAnalyticsArtifactsResponseItemStatus | None = None


class GetOrganizationCameraCustomAnalyticsArtifactsResponse(
    RootModel[list[GetOrganizationCameraCustomAnalyticsArtifactsResponseItem]]
):
    """List Custom Analytics Artifacts."""


class GetOrganizationCameraDetectionsHistoryByBoundaryByIntervalResponseItem(_BaseSchema):
    """Schema for GetOrganizationCameraDetectionsHistoryByBoundaryByIntervalResponseItem."""

    boundary_id: str | None = Field(default=None, alias="boundaryId")
    type_: str | None = Field(default=None, alias="type")
    results: (
        GetOrganizationCameraDetectionsHistoryByBoundaryByIntervalResponseItemResults | None
    ) = None


class GetOrganizationCameraDetectionsHistoryByBoundaryByIntervalResponse(
    RootModel[list[GetOrganizationCameraDetectionsHistoryByBoundaryByIntervalResponseItem]]
):
    """Returns analytics data for timespans."""
