"""Response schemas for campus_gateway endpoints.

This module is automatically @generated from the Meraki API specification.
Do not edit this file manually.
"""

from __future__ import annotations

from pydantic import Field

from meraki_client.schemas._base import _BaseSchema


class CampusGatewayAddressesItem(_BaseSchema):
    """Schema for CampusGatewayAddressesItem."""

    protocol: str | None = None
    address: str | None = None


class CampusGatewayAddressesItem2(_BaseSchema):
    """Schema for CampusGatewayAddressesItem2."""

    assignment_mode: str | None = Field(default=None, alias="assignmentMode")
    protocol: str | None = None
    gateway: str | None = None
    subnet_mask: str | None = Field(default=None, alias="subnetMask")
    address: str | None = None


class CampusGatewayDevicesUplinksItem(_BaseSchema):
    """Schema for CampusGatewayDevicesUplinksItem."""

    interface: str | None = None
    addresses: list[CampusGatewayAddressesItem] | None = None


class CampusGatewayItems(_BaseSchema):
    """The count metadata."""

    total: int | None = None
    remaining: int | None = None


class CampusGatewayItemsItem(_BaseSchema):
    """Schema for CampusGatewayItemsItem."""

    serial: str | None = None
    uplink: CampusGatewayUplink | None = None
    nameservers: CreateNetworkCampusGatewayClusterResponseNameservers | None = None
    sgt: int | None = None


class CampusGatewayMetaCounts(_BaseSchema):
    """Count metadata related to this result set."""

    items: CampusGatewayItems | None = None


class CampusGatewayNetwork(_BaseSchema):
    """Network details of the cluster."""

    id_: str | None = Field(default=None, alias="id")


class CampusGatewayTunnelsAddressesItem(_BaseSchema):
    """Schema for CampusGatewayTunnelsAddressesItem."""

    protocol: str | None = None
    gateway: str | None = None
    subnet_mask: str | None = Field(default=None, alias="subnetMask")


class CampusGatewayTunnelsUplink(_BaseSchema):
    """Use uplink interface as tunnel interface."""

    interface: str | None = None


class CampusGatewayUplink(_BaseSchema):
    """Uplink setting of the cluster."""

    interface: str | None = None
    vlan: int | None = None
    addresses: list[CampusGatewayAddressesItem2] | None = None


class CampusGatewayUplinksAddressesItem(_BaseSchema):
    """Schema for CampusGatewayUplinksAddressesItem."""

    assignment_mode: str | None = Field(default=None, alias="assignmentMode")
    protocol: str | None = None
    gateway: str | None = None
    subnet_mask: str | None = Field(default=None, alias="subnetMask")


class CreateNetworkCampusGatewayClusterResponse(_BaseSchema):
    """Response for createNetworkCampusGatewayCluster operation."""

    cluster_id: str | None = Field(default=None, alias="clusterId")
    name: str | None = None
    uplinks: list[CreateNetworkCampusGatewayClusterResponseUplinksItem] | None = None
    tunnels: list[CreateNetworkCampusGatewayClusterResponseTunnelsItem] | None = None
    nameservers: CreateNetworkCampusGatewayClusterResponseNameservers | None = None
    port_channels: list[CreateNetworkCampusGatewayClusterResponsePortChannelsItem] | None = Field(
        default=None, alias="portChannels"
    )
    devices: list[CreateNetworkCampusGatewayClusterResponseDevicesItem] | None = None
    notes: str | None = None
    url: str | None = None


class CreateNetworkCampusGatewayClusterResponseDevicesItem(_BaseSchema):
    """Schema for CreateNetworkCampusGatewayClusterResponseDevicesItem."""

    serial: str | None = None
    member_id: str | None = Field(default=None, alias="memberId")
    uplinks: list[CampusGatewayDevicesUplinksItem] | None = None
    tunnels: list[CampusGatewayDevicesUplinksItem] | None = None


class CreateNetworkCampusGatewayClusterResponseNameservers(_BaseSchema):
    """Nameservers of the cluster."""

    addresses: list[str] | None = None


class CreateNetworkCampusGatewayClusterResponsePortChannelsItem(_BaseSchema):
    """Schema for CreateNetworkCampusGatewayClusterResponsePortChannelsItem."""

    id_: str | None = Field(default=None, alias="id")
    name: str | None = None
    vlan: int | None = None
    allowed_vlans: str | None = Field(default=None, alias="allowedVlans")


class CreateNetworkCampusGatewayClusterResponseTunnelsItem(_BaseSchema):
    """Schema for CreateNetworkCampusGatewayClusterResponseTunnelsItem."""

    uplink: CampusGatewayTunnelsUplink | None = None
    interface: str | None = None
    vlan: int | None = None
    addresses: list[CampusGatewayTunnelsAddressesItem] | None = None


class CreateNetworkCampusGatewayClusterResponseUplinksItem(_BaseSchema):
    """Schema for CreateNetworkCampusGatewayClusterResponseUplinksItem."""

    interface: str | None = None
    vlan: int | None = None
    addresses: list[CampusGatewayUplinksAddressesItem] | None = None


class GetOrganizationCampusGatewayClustersResponse(_BaseSchema):
    """Response for getOrganizationCampusGatewayClusters operation."""

    items: list[GetOrganizationCampusGatewayClustersResponseItemsItem] | None = None
    meta: GetOrganizationCampusGatewayClustersResponseMeta | None = None


class GetOrganizationCampusGatewayClustersResponseItemsItem(_BaseSchema):
    """Schema for GetOrganizationCampusGatewayClustersResponseItemsItem."""

    network: CampusGatewayNetwork | None = None
    cluster_id: str | None = Field(default=None, alias="clusterId")
    name: str | None = None
    uplinks: list[CreateNetworkCampusGatewayClusterResponseUplinksItem] | None = None
    tunnels: list[CreateNetworkCampusGatewayClusterResponseTunnelsItem] | None = None
    nameservers: CreateNetworkCampusGatewayClusterResponseNameservers | None = None
    port_channels: list[CreateNetworkCampusGatewayClusterResponsePortChannelsItem] | None = Field(
        default=None, alias="portChannels"
    )
    devices: list[CreateNetworkCampusGatewayClusterResponseDevicesItem] | None = None
    notes: str | None = None
    url: str | None = None


class GetOrganizationCampusGatewayClustersResponseMeta(_BaseSchema):
    """Other metadata related to this result set."""

    counts: CampusGatewayMetaCounts | None = None


class GetOrganizationCampusGatewayDevicesUplinksLocalOverridesByDeviceResponse(_BaseSchema):
    """Response for getOrganizationCampusGatewayDevicesUplinksLocalOverridesByDevice operation."""

    items: list[CampusGatewayItemsItem] | None = None
    meta: GetOrganizationCampusGatewayClustersResponseMeta | None = None


class UpdateNetworkCampusGatewayClusterResponse(_BaseSchema):
    """Response for updateNetworkCampusGatewayCluster operation."""

    cluster_id: str | None = Field(default=None, alias="clusterId")
    name: str | None = None
    uplinks: list[CreateNetworkCampusGatewayClusterResponseUplinksItem] | None = None
    tunnels: list[CreateNetworkCampusGatewayClusterResponseTunnelsItem] | None = None
    nameservers: CreateNetworkCampusGatewayClusterResponseNameservers | None = None
    port_channels: list[CreateNetworkCampusGatewayClusterResponsePortChannelsItem] | None = Field(
        default=None, alias="portChannels"
    )
    devices: list[CreateNetworkCampusGatewayClusterResponseDevicesItem] | None = None
    notes: str | None = None
    url: str | None = None
