"""Response schemas for devices endpoints.

This module is automatically @generated from the Meraki API specification.
Do not edit this file manually.
"""

from typing import Any

from pydantic import Field, RootModel

from meraki_client.schemas._base import _BaseSchema


class GetDeviceResponseDetailsItem(_BaseSchema):
    """Schema for GetDeviceResponseDetailsItem."""

    name: str | None = None
    value: str | None = None


class GetDeviceResponseBeaconIdParams(_BaseSchema):
    """Beacon Id parameters with an identifier and major and minor versions."""

    uuid: str | None = None
    major: int | None = None
    minor: int | None = None


class BlinkDeviceLedsResponse(_BaseSchema):
    """Blink the LEDs on a device. This endpoint is deprecrated in favor of
    "/devices/{serial}/liveTools/leds/blink".
    """

    duration: int | None = None
    period: int | None = None
    duty: int | None = None


class DevicesAuthentication(_BaseSchema):
    """APN authentication configurations."""

    type_: str | None = Field(default=None, alias="type")
    username: str | None = None
    password: str | None = None


class GetDeviceCellularSimsResponseSimFailover(_BaseSchema):
    """SIM Failover settings."""

    enabled: bool | None = None
    timeout: int | None = None


class DevicesUsage(_BaseSchema):
    """Client usage data for sent and received."""

    sent: float | None = None
    recv: float | None = None


class CreateDeviceLiveToolsArpTableResponseRequest(_BaseSchema):
    """ARP table request parameters."""

    serial: str | None = None


class CreateDeviceLiveToolsArpTableResponseCallback(_BaseSchema):
    """Information for callback used to send back results."""

    id_: str | None = Field(default=None, alias="id")
    url: str | None = None
    status: str | None = None


class GetDeviceLiveToolsArpTableResponseEntriesItem(_BaseSchema):
    """Schema for GetDeviceLiveToolsArpTableResponseEntriesItem."""

    ip: str | None = None
    mac: str | None = None
    vlan_id: int | None = Field(default=None, alias="vlanId")
    interface: str | None = None
    last_updated_at: str | None = Field(default=None, alias="lastUpdatedAt")


class CreateDeviceLiveToolsCableTestResponseRequest(_BaseSchema):
    """Cable test request parameters."""

    serial: str | None = None
    ports: list[str] | None = None


class DevicesResultsPairsItem(_BaseSchema):
    """Schema for DevicesResultsPairsItem."""

    index: int | None = None
    status: str | None = None
    length_meters: int | None = Field(default=None, alias="lengthMeters")


class CreateDeviceLiveToolsLedsBlinkResponseRequest(_BaseSchema):
    """The parameters of the leds blink request."""

    serial: str | None = None
    duration: int | None = None


class GetDeviceLiveToolsMacTableResponseEntriesItem(_BaseSchema):
    """Schema for GetDeviceLiveToolsMacTableResponseEntriesItem."""

    mac: str | None = None
    port: str | None = None
    vlan_id: int | None = Field(default=None, alias="vlanId")


class GetDeviceLiveToolsMulticastRoutingResponseInterfacesItem(_BaseSchema):
    """Schema for GetDeviceLiveToolsMulticastRoutingResponseInterfacesItem."""

    ip: str | None = None
    name: str | None = None
    subnet: str | None = None
    flags: list[str] | None = None
    neighbors: list[str] | None = None


class GetDeviceLiveToolsMulticastRoutingResponseRoutesItem(_BaseSchema):
    """Schema for GetDeviceLiveToolsMulticastRoutingResponseRoutesItem."""

    source: str | None = None
    group: str | None = None
    rendezvous_point: str | None = Field(default=None, alias="rendezvousPoint")
    incoming_interface_name: str | None = Field(default=None, alias="incomingInterfaceName")
    outgoing_interface_names: list[str] | None = Field(default=None, alias="outgoingInterfaceNames")
    flags: list[str] | None = None


class CreateDeviceLiveToolsPingResponseRequest(_BaseSchema):
    """Ping request parameters."""

    serial: str | None = None
    target: str | None = None
    count: int | None = None


class DevicesResultsLoss(_BaseSchema):
    """Lost packets."""

    percentage: float | None = None


class DevicesResultsLatencies(_BaseSchema):
    """Packet latency stats."""

    minimum: float | None = None
    average: float | None = None
    maximum: float | None = None


class DevicesResultsRepliesItem(_BaseSchema):
    """Schema for DevicesResultsRepliesItem."""

    sequence_id: int | None = Field(default=None, alias="sequenceId")
    size: int | None = None
    latency: float | None = None


class CreateDeviceLiveToolsPingDeviceResponseRequest(_BaseSchema):
    """Ping request parameters."""

    serial: str | None = None
    count: int | None = None


class DevicesResultSpeeds(_BaseSchema):
    """Shows the speeds (Mbps)."""

    downstream: float | None = None


class CreateDeviceLiveToolsWakeOnLanResponseRequest(_BaseSchema):
    """The parameters of the Wake-on-LAN request."""

    serial: str | None = None
    vlan_id: int | None = Field(default=None, alias="vlanId")
    mac: str | None = None


class GetDeviceLldpCdpResponse(_BaseSchema):
    """List LLDP and CDP information for a device."""

    source_mac: str | None = Field(default=None, alias="sourceMac")
    ports: dict[str, Any] | None = None


class GetDeviceLossAndLatencyHistoryResponseItem(_BaseSchema):
    """Schema for GetDeviceLossAndLatencyHistoryResponseItem."""

    start_time: str | None = Field(default=None, alias="startTime")
    end_time: str | None = Field(default=None, alias="endTime")
    loss_percent: float | None = Field(default=None, alias="lossPercent")
    latency_ms: float | None = Field(default=None, alias="latencyMs")
    goodput: int | None = None
    jitter: float | None = None


class GetDeviceManagementInterfaceResponseDdnsHostnames(_BaseSchema):
    """Dynamic DNS hostnames."""

    active_ddns_hostname: str | None = Field(default=None, alias="activeDdnsHostname")
    ddns_hostname_wan1: str | None = Field(default=None, alias="ddnsHostnameWan1")
    ddns_hostname_wan2: str | None = Field(default=None, alias="ddnsHostnameWan2")


class DevicesWan1Vrf(_BaseSchema):
    """VRF associated with the management interface. If not provided, the default VRF is used."""

    name: str | None = None


class RebootDeviceResponse(_BaseSchema):
    """Reboot a device. This endpoint has a sustained rate limit of one request every 60 seconds."""

    success: bool | None = None


class GetDeviceResponse(_BaseSchema):
    """Return a single device."""

    name: str | None = None
    lat: float | None = None
    lng: float | None = None
    address: str | None = None
    notes: str | None = None
    tags: list[str] | None = None
    network_id: str | None = Field(default=None, alias="networkId")
    serial: str | None = None
    model: str | None = None
    mac: str | None = None
    lan_ip: str | None = Field(default=None, alias="lanIp")
    firmware: str | None = None
    floor_plan_id: str | None = Field(default=None, alias="floorPlanId")
    details: list[GetDeviceResponseDetailsItem] | None = None
    beacon_id_params: GetDeviceResponseBeaconIdParams | None = Field(
        default=None, alias="beaconIdParams"
    )


class DevicesSimsApnsItem(_BaseSchema):
    """Schema for DevicesSimsApnsItem."""

    name: str
    allowed_ip_types: list[str] = Field(alias="allowedIpTypes")
    authentication: DevicesAuthentication | None = None


class GetDeviceClientsResponseItem(_BaseSchema):
    """Schema for GetDeviceClientsResponseItem."""

    id_: str | None = Field(default=None, alias="id")
    mac: str | None = None
    description: str | None = None
    mdns_name: str | None = Field(default=None, alias="mdnsName")
    dhcp_hostname: str | None = Field(default=None, alias="dhcpHostname")
    user: str | None = None
    ip: str | None = None
    vlan: str | None = None
    named_vlan: str | None = Field(default=None, alias="namedVlan")
    switchport: str | None = None
    adaptive_policy_group: str | None = Field(default=None, alias="adaptivePolicyGroup")
    usage: DevicesUsage | None = None


class CreateDeviceLiveToolsArpTableResponse(_BaseSchema):
    """Enqueue a job to perform a ARP table request for the device. This endpoint currently
    supports switches, wireless access points, and catalyst routers. This endpoint has a
    sustained rate limit of one request every five seconds per device, with an allowed burst of
    five requests.
    """

    arp_table_id: str | None = Field(default=None, alias="arpTableId")
    url: str | None = None
    request: CreateDeviceLiveToolsArpTableResponseRequest | None = None
    status: str | None = None
    callback: CreateDeviceLiveToolsArpTableResponseCallback | None = None


class GetDeviceLiveToolsCableTestResponseResultsItem(_BaseSchema):
    """Schema for GetDeviceLiveToolsCableTestResponseResultsItem."""

    port: str | None = None
    status: str | None = None
    speed_mbps: int | None = Field(default=None, alias="speedMbps")
    error: str | None = None
    pairs: list[DevicesResultsPairsItem] | None = None


class GetDeviceLiveToolsPingResponseResults(_BaseSchema):
    """Results of the ping request."""

    sent: int | None = None
    received: int | None = None
    loss: DevicesResultsLoss | None = None
    latencies: DevicesResultsLatencies | None = None
    replies: list[DevicesResultsRepliesItem] | None = None


class CreateDeviceLiveToolsThroughputTestResponseResult(_BaseSchema):
    """Result of the throughput test request."""

    speeds: DevicesResultSpeeds | None = None


class GetDeviceLossAndLatencyHistoryResponse(
    RootModel[list[GetDeviceLossAndLatencyHistoryResponseItem]]
):
    """Get the uplink loss percentage and latency in milliseconds, and goodput in kilobits per
    second for MX, MG and Z devices.
    """


class GetDeviceManagementInterfaceResponseWan1(_BaseSchema):
    """WAN 1 settings."""

    wan_enabled: str | None = Field(default=None, alias="wanEnabled")
    using_static_ip: bool | None = Field(default=None, alias="usingStaticIp")
    static_ip: str | None = Field(default=None, alias="staticIp")
    static_subnet_mask: str | None = Field(default=None, alias="staticSubnetMask")
    static_gateway_ip: str | None = Field(default=None, alias="staticGatewayIp")
    static_dns: list[str] | None = Field(default=None, alias="staticDns")
    vlan: int | None = None
    vrf: DevicesWan1Vrf | None = None


class UpdateDeviceResponse(_BaseSchema):
    """Update the attributes of a device."""

    name: str | None = None
    lat: float | None = None
    lng: float | None = None
    address: str | None = None
    notes: str | None = None
    tags: list[str] | None = None
    network_id: str | None = Field(default=None, alias="networkId")
    serial: str | None = None
    model: str | None = None
    mac: str | None = None
    lan_ip: str | None = Field(default=None, alias="lanIp")
    firmware: str | None = None
    floor_plan_id: str | None = Field(default=None, alias="floorPlanId")
    details: list[GetDeviceResponseDetailsItem] | None = None
    beacon_id_params: GetDeviceResponseBeaconIdParams | None = Field(
        default=None, alias="beaconIdParams"
    )


class GetDeviceCellularSimsResponseSimsItem(_BaseSchema):
    """Schema for GetDeviceCellularSimsResponseSimsItem."""

    slot: str | None = None
    iccid: str | None = None
    imsi: str | None = None
    msisdn: str | None = None
    is_primary: bool | None = Field(default=None, alias="isPrimary")
    status: str | None = None
    apns: list[DevicesSimsApnsItem] | None = None


class GetDeviceClientsResponse(RootModel[list[GetDeviceClientsResponseItem]]):
    """List the clients of a device, up to a maximum of a month ago. The usage of each client is
    returned in kilobytes. If the device is a switch, the switchport is returned; otherwise the
    switchport field is null.
    """


class GetDeviceLiveToolsArpTableResponse(_BaseSchema):
    """Return an ARP table live tool job."""

    arp_table_id: str | None = Field(default=None, alias="arpTableId")
    url: str | None = None
    request: CreateDeviceLiveToolsArpTableResponseRequest | None = None
    status: str | None = None
    entries: list[GetDeviceLiveToolsArpTableResponseEntriesItem] | None = None
    error: str | None = None


class CreateDeviceLiveToolsCableTestResponse(_BaseSchema):
    """Enqueue a job to perform a cable test for the device on the specified ports. This endpoint
    has a sustained rate limit of one request every five seconds per device, with an allowed
    burst of five requests.
    """

    cable_test_id: str | None = Field(default=None, alias="cableTestId")
    url: str | None = None
    request: CreateDeviceLiveToolsCableTestResponseRequest | None = None
    status: str | None = None
    callback: CreateDeviceLiveToolsArpTableResponseCallback | None = None


class CreateDeviceLiveToolsLedsBlinkResponse(_BaseSchema):
    """Enqueue a job to blink LEDs on a device. This endpoint has a rate limit of one request every
    10 seconds.
    """

    leds_blink_id: str | None = Field(default=None, alias="ledsBlinkId")
    url: str | None = None
    status: str | None = None
    request: CreateDeviceLiveToolsLedsBlinkResponseRequest | None = None
    error: str | None = None
    callback: CreateDeviceLiveToolsArpTableResponseCallback | None = None


class CreateDeviceLiveToolsMacTableResponse(_BaseSchema):
    """Enqueue a job to request the MAC table from the device. Switches currently support this
    feature. This endpoint has a sustained rate limit of one request every five seconds per
    device, with an allowed burst of five requests.
    """

    mac_table_id: str | None = Field(default=None, alias="macTableId")
    url: str | None = None
    request: CreateDeviceLiveToolsArpTableResponseRequest | None = None
    status: str | None = None
    callback: CreateDeviceLiveToolsArpTableResponseCallback | None = None


class GetDeviceLiveToolsMacTableResponse(_BaseSchema):
    """Return a MAC table live tool job."""

    mac_table_id: str | None = Field(default=None, alias="macTableId")
    url: str | None = None
    request: CreateDeviceLiveToolsArpTableResponseRequest | None = None
    status: str | None = None
    entries: list[GetDeviceLiveToolsMacTableResponseEntriesItem] | None = None
    error: str | None = None


class CreateDeviceLiveToolsMulticastRoutingResponse(_BaseSchema):
    """Enqueue a job to perform a Multicast routing request for the device. This endpoint currently
    supports switches. This endpoint has a sustained rate limit of one request every five
    seconds per device, with an allowed burst of five requests.
    """

    multicast_routing_id: str | None = Field(default=None, alias="multicastRoutingId")
    url: str | None = None
    request: CreateDeviceLiveToolsArpTableResponseRequest | None = None
    status: str | None = None
    callback: CreateDeviceLiveToolsArpTableResponseCallback | None = None


class GetDeviceLiveToolsMulticastRoutingResponse(_BaseSchema):
    """Return a Multicast routing live tool job."""

    multicast_routing_id: str | None = Field(default=None, alias="multicastRoutingId")
    url: str | None = None
    request: CreateDeviceLiveToolsArpTableResponseRequest | None = None
    status: str | None = None
    interfaces: list[GetDeviceLiveToolsMulticastRoutingResponseInterfacesItem] | None = None
    routes: list[GetDeviceLiveToolsMulticastRoutingResponseRoutesItem] | None = None
    error: str | None = None


class CreateDeviceLiveToolsPingResponse(_BaseSchema):
    """Enqueue a job to ping a target host from the device. This endpoint has a sustained rate
    limit of one request every five seconds per device, with an allowed burst of five requests.
    """

    ping_id: str | None = Field(default=None, alias="pingId")
    url: str | None = None
    request: CreateDeviceLiveToolsPingResponseRequest | None = None
    status: str | None = None
    callback: CreateDeviceLiveToolsArpTableResponseCallback | None = None


class CreateDeviceLiveToolsPingDeviceResponse(_BaseSchema):
    """Enqueue a job to check connectivity status to the device. This endpoint has a sustained rate
    limit of one request every five seconds per device, with an allowed burst of five requests.
    """

    ping_id: str | None = Field(default=None, alias="pingId")
    url: str | None = None
    request: CreateDeviceLiveToolsPingDeviceResponseRequest | None = None
    status: str | None = None
    callback: CreateDeviceLiveToolsArpTableResponseCallback | None = None


class CreateDeviceLiveToolsWakeOnLanResponse(_BaseSchema):
    """Enqueue a job to send a Wake-on-LAN packet from the device. This endpoint has a sustained
    rate limit of one request every five seconds per device, with an allowed burst of five
    requests.
    """

    wake_on_lan_id: str | None = Field(default=None, alias="wakeOnLanId")
    url: str | None = None
    status: str | None = None
    request: CreateDeviceLiveToolsWakeOnLanResponseRequest | None = None
    error: str | None = None
    callback: CreateDeviceLiveToolsArpTableResponseCallback | None = None


class CreateDeviceLiveToolsThroughputTestResponse(_BaseSchema):
    """Enqueue a job to test a device throughput, the test will run for 10 secs to test throughput.
    This endpoint has a rate limit of one request every five seconds per device.
    """

    throughput_test_id: str | None = Field(default=None, alias="throughputTestId")
    url: str | None = None
    status: str | None = None
    result: CreateDeviceLiveToolsThroughputTestResponseResult | None = None
    request: CreateDeviceLiveToolsArpTableResponseRequest | None = None
    error: str | None = None
    callback: CreateDeviceLiveToolsArpTableResponseCallback | None = None


class GetDeviceManagementInterfaceResponse(_BaseSchema):
    """Return the management interface settings for a device."""

    ddns_hostnames: GetDeviceManagementInterfaceResponseDdnsHostnames | None = Field(
        default=None, alias="ddnsHostnames"
    )
    wan1: GetDeviceManagementInterfaceResponseWan1 | None = None
    wan2: GetDeviceManagementInterfaceResponseWan1 | None = None


class GetDeviceCellularSimsResponse(_BaseSchema):
    """Return the SIM and APN configurations for a cellular device."""

    sims: list[GetDeviceCellularSimsResponseSimsItem] | None = None
    sim_ordering: list[str] | None = Field(default=None, alias="simOrdering")
    sim_failover: GetDeviceCellularSimsResponseSimFailover | None = Field(
        default=None, alias="simFailover"
    )


class GetDeviceLiveToolsCableTestResponse(_BaseSchema):
    """Return a cable test live tool job."""

    cable_test_id: str | None = Field(default=None, alias="cableTestId")
    url: str | None = None
    request: CreateDeviceLiveToolsCableTestResponseRequest | None = None
    status: str | None = None
    results: list[GetDeviceLiveToolsCableTestResponseResultsItem] | None = None
    error: str | None = None


class GetDeviceLiveToolsLedsBlinkResponse(_BaseSchema):
    """Return a blink LEDs job."""

    leds_blink_id: str | None = Field(default=None, alias="ledsBlinkId")
    url: str | None = None
    status: str | None = None
    request: CreateDeviceLiveToolsLedsBlinkResponseRequest | None = None
    error: str | None = None


class GetDeviceLiveToolsPingResponse(_BaseSchema):
    """Return a ping job. Latency unit in response is in milliseconds. Size is in bytes."""

    ping_id: str | None = Field(default=None, alias="pingId")
    url: str | None = None
    request: CreateDeviceLiveToolsPingResponseRequest | None = None
    status: str | None = None
    results: GetDeviceLiveToolsPingResponseResults | None = None


class GetDeviceLiveToolsWakeOnLanResponse(_BaseSchema):
    """Return a Wake-on-LAN job."""

    wake_on_lan_id: str | None = Field(default=None, alias="wakeOnLanId")
    url: str | None = None
    status: str | None = None
    request: CreateDeviceLiveToolsWakeOnLanResponseRequest | None = None
    error: str | None = None


class GetDeviceLiveToolsThroughputTestResponse(_BaseSchema):
    """Return a throughput test job."""

    throughput_test_id: str | None = Field(default=None, alias="throughputTestId")
    url: str | None = None
    status: str | None = None
    result: CreateDeviceLiveToolsThroughputTestResponseResult | None = None
    request: CreateDeviceLiveToolsArpTableResponseRequest | None = None
    error: str | None = None


class UpdateDeviceManagementInterfaceResponse(_BaseSchema):
    """Update the management interface settings for a device."""

    ddns_hostnames: GetDeviceManagementInterfaceResponseDdnsHostnames | None = Field(
        default=None, alias="ddnsHostnames"
    )
    wan1: GetDeviceManagementInterfaceResponseWan1 | None = None
    wan2: GetDeviceManagementInterfaceResponseWan1 | None = None


class UpdateDeviceCellularSimsResponse(_BaseSchema):
    """Updates the SIM and APN configurations for a cellular device."""

    sims: list[GetDeviceCellularSimsResponseSimsItem] | None = None
    sim_ordering: list[str] | None = Field(default=None, alias="simOrdering")
    sim_failover: GetDeviceCellularSimsResponseSimFailover | None = Field(
        default=None, alias="simFailover"
    )


class GetDeviceLiveToolsPingDeviceResponse(_BaseSchema):
    """Return a ping device job. Latency unit in response is in milliseconds. Size is in bytes."""

    ping_id: str | None = Field(default=None, alias="pingId")
    url: str | None = None
    request: CreateDeviceLiveToolsPingDeviceResponseRequest | None = None
    status: str | None = None
    results: GetDeviceLiveToolsPingResponseResults | None = None
    callback: CreateDeviceLiveToolsArpTableResponseCallback | None = None
