"""Response schemas for networks endpoints.

This module is automatically @generated from the Meraki API specification.
Do not edit this file manually.
"""

from typing import Any

from pydantic import Field, RootModel

from meraki_client.schemas._base import _BaseSchema


class GetNetworkResponse(_BaseSchema):
    """Return a network."""

    id_: str | None = Field(default=None, alias="id")
    organization_id: str | None = Field(default=None, alias="organizationId")
    name: str | None = None
    product_types: list[str] | None = Field(default=None, alias="productTypes")
    time_zone: str | None = Field(default=None, alias="timeZone")
    tags: list[str] | None = None
    enrollment_string: str | None = Field(default=None, alias="enrollmentString")
    url: str | None = None
    notes: str | None = None
    is_bound_to_config_template: bool | None = Field(default=None, alias="isBoundToConfigTemplate")


class UpdateNetworkResponse(_BaseSchema):
    """Update a network."""

    id_: str | None = Field(default=None, alias="id")
    organization_id: str | None = Field(default=None, alias="organizationId")
    name: str | None = None
    product_types: list[str] | None = Field(default=None, alias="productTypes")
    time_zone: str | None = Field(default=None, alias="timeZone")
    tags: list[str] | None = None
    enrollment_string: str | None = Field(default=None, alias="enrollmentString")
    url: str | None = None
    notes: str | None = None
    is_bound_to_config_template: bool | None = Field(default=None, alias="isBoundToConfigTemplate")


class NetworksDevice(_BaseSchema):
    """info related to the device that caused the alert."""

    serial: str | None = None


class NetworksEmail(_BaseSchema):
    """email destinations for this alert."""

    sent_at: str | None = Field(default=None, alias="sentAt")


class GetNetworkAlertsSettingsResponseDefaultDestinations(_BaseSchema):
    """The network-wide destinations for all alerts on the network."""

    emails: list[str] | None = None
    all_admins: bool | None = Field(default=None, alias="allAdmins")
    snmp: bool | None = None
    http_server_ids: list[str] | None = Field(default=None, alias="httpServerIds")


class NetworksAlertsAlertDestinations(_BaseSchema):
    """A hash of destinations for this specific alert."""

    emails: list[str] | None = None
    sms_numbers: list[str] | None = Field(default=None, alias="smsNumbers")
    all_admins: bool | None = Field(default=None, alias="allAdmins")
    snmp: bool | None = None
    http_server_ids: list[str] | None = Field(default=None, alias="httpServerIds")


class NetworksConditionsItem(_BaseSchema):
    """Schema for NetworksConditionsItem."""

    type_: str | None = Field(default=None, alias="type")
    unit: str | None = None
    duration: int | None = None
    direction: str | None = None
    threshold: float | None = None


class NetworksMutingByPortSchedules(_BaseSchema):
    """Mute wireless unreachable alerts based on switch port schedules."""

    enabled: bool | None = None


class BindNetworkResponse(_BaseSchema):
    """Bind a network to a template."""

    id_: str | None = Field(default=None, alias="id")
    organization_id: str | None = Field(default=None, alias="organizationId")
    name: str | None = None
    product_types: list[str] | None = Field(default=None, alias="productTypes")
    time_zone: str | None = Field(default=None, alias="timeZone")
    tags: list[str] | None = None
    enrollment_string: str | None = Field(default=None, alias="enrollmentString")
    url: str | None = None
    notes: str | None = None
    is_bound_to_config_template: bool | None = Field(default=None, alias="isBoundToConfigTemplate")
    config_template_id: str | None = Field(default=None, alias="configTemplateId")


class GetNetworkBluetoothClientsResponseItem(_BaseSchema):
    """Schema for GetNetworkBluetoothClientsResponseItem."""

    id_: str | None = Field(default=None, alias="id")
    mac: str | None = None
    network_id: str | None = Field(default=None, alias="networkId")
    name: str | None = None
    device_name: str | None = Field(default=None, alias="deviceName")
    manufacturer: str | None = None
    last_seen: int | None = Field(default=None, alias="lastSeen")
    seen_by_device_mac: str | None = Field(default=None, alias="seenByDeviceMac")
    in_sight_alert: bool | None = Field(default=None, alias="inSightAlert")
    out_of_sight_alert: bool | None = Field(default=None, alias="outOfSightAlert")
    tags: list[str] | None = None


class GetNetworkBluetoothClientResponse(_BaseSchema):
    """Return a Bluetooth client. Bluetooth clients can be identified by their ID or their MAC."""

    id_: str | None = Field(default=None, alias="id")
    mac: str | None = None
    network_id: str | None = Field(default=None, alias="networkId")
    name: str | None = None
    device_name: str | None = Field(default=None, alias="deviceName")
    manufacturer: str | None = None
    last_seen: int | None = Field(default=None, alias="lastSeen")
    seen_by_device_mac: str | None = Field(default=None, alias="seenByDeviceMac")
    in_sight_alert: bool | None = Field(default=None, alias="inSightAlert")
    out_of_sight_alert: bool | None = Field(default=None, alias="outOfSightAlert")
    tags: list[str] | None = None


class NetworksUsage(_BaseSchema):
    """Usage, sent and received."""

    sent: float | None = None
    recv: float | None = None


class NetworksApplicationUsageItem(_BaseSchema):
    """Schema for NetworksApplicationUsageItem."""

    application: str | None = None
    received: int | None = None
    sent: int | None = None


class GetNetworkClientsBandwidthUsageHistoryResponseItem(_BaseSchema):
    """Schema for GetNetworkClientsBandwidthUsageHistoryResponseItem."""

    ts: str | None = None
    total: float | None = None
    upstream: float | None = None
    downstream: float | None = None


class GetNetworkClientsOverviewResponseCounts(_BaseSchema):
    """The number of clients on a network over a given time range."""

    total: int | None = None
    with_heavy_usage: int | None = Field(default=None, alias="withHeavyUsage")


class GetNetworkClientsOverviewResponseUsages(_BaseSchema):
    """The average usage of the clients on a network over a given time range."""

    average: int | None = None
    with_heavy_usage_average: int | None = Field(default=None, alias="withHeavyUsageAverage")


class ProvisionNetworkClientsResponseClientsItem(_BaseSchema):
    """Schema for ProvisionNetworkClientsResponseClientsItem."""

    mac: str | None = None
    client_id: str | None = Field(default=None, alias="clientId")
    name: str | None = None
    message: str | None = None


class NetworksUsageHistoryItem(_BaseSchema):
    """Schema for NetworksUsageHistoryItem."""

    received: float | None = None
    sent: float | None = None
    ts: str | None = None


class GetNetworkClientResponseClientVpnConnectionsItem(_BaseSchema):
    """Schema for GetNetworkClientResponseClientVpnConnectionsItem."""

    remote_ip: str | None = Field(default=None, alias="remoteIp")
    connected_at: int | None = Field(default=None, alias="connectedAt")
    disconnected_at: int | None = Field(default=None, alias="disconnectedAt")


class GetNetworkClientPolicyResponsePoliciesBySsidItem(_BaseSchema):
    """Schema for GetNetworkClientPolicyResponsePoliciesBySsidItem."""

    ssid_number: int | None = Field(default=None, alias="ssidNumber")
    device_policy: str | None = Field(default=None, alias="devicePolicy")
    group_policy_id: str | None = Field(default=None, alias="groupPolicyId")


class GetNetworkClientTrafficHistoryResponseItem(_BaseSchema):
    """Schema for GetNetworkClientTrafficHistoryResponseItem."""

    ts: str | None = None
    application: str | None = None
    destination: str | None = None
    protocol: str | None = None
    port: int | None = None
    recv: float | None = None
    sent: float | None = None
    num_flows: int | None = Field(default=None, alias="numFlows")
    active_seconds: int | None = Field(default=None, alias="activeSeconds")


class GetNetworkClientUsageHistoryResponseItem(_BaseSchema):
    """Schema for GetNetworkClientUsageHistoryResponseItem."""

    received: float | None = None
    sent: float | None = None
    ts: str | None = None


class NetworksDetailsItem(_BaseSchema):
    """Schema for NetworksDetailsItem."""

    name: str | None = None
    value: str | None = None


class NetworksBeaconIdParams(_BaseSchema):
    """Beacon Id parameters with an identifier and major and minor versions."""

    uuid: str | None = None
    major: int | None = None
    minor: int | None = None


class ClaimNetworkDevicesResponseErrorsItem(_BaseSchema):
    """Schema for ClaimNetworkDevicesResponseErrorsItem."""

    serial: str
    errors: list[str]


class NetworksEventsEventData(_BaseSchema):
    """An object containing more data related to the event."""

    radio: str | None = None
    vap: str | None = None
    client_mac: str | None = None
    client_ip: str | None = None
    channel: str | None = None
    rssi: str | None = None
    aid: str | None = None


class GetNetworkEventsEventTypesResponseItem(_BaseSchema):
    """Schema for GetNetworkEventsEventTypesResponseItem."""

    category: str | None = None
    type_: str | None = Field(default=None, alias="type")
    description: str | None = None


class GetNetworkFirmwareUpgradesResponseUpgradeWindow(_BaseSchema):
    """Upgrade window for devices in network."""

    day_of_week: str | None = Field(default=None, alias="dayOfWeek")
    hour_of_day: str | None = Field(default=None, alias="hourOfDay")


class NetworksCurrentVersion(_BaseSchema):
    """Details of the current version on the device."""

    id_: str | None = Field(default=None, alias="id")
    firmware: str | None = None
    short_name: str | None = Field(default=None, alias="shortName")
    release_type: str | None = Field(default=None, alias="releaseType")
    release_date: str | None = Field(default=None, alias="releaseDate")


class CreateNetworkFirmwareUpgradesRollbackResponseReasonsItem(_BaseSchema):
    """Schema for CreateNetworkFirmwareUpgradesRollbackResponseReasonsItem."""

    category: str | None = None
    comment: str | None = None


class NetworksToVersion(_BaseSchema):
    """Details of the version the device will upgrade to."""

    id_: str | None = Field(default=None, alias="id")
    short_name: str | None = Field(default=None, alias="shortName")


class NetworksStagesGroup(_BaseSchema):
    """The staged upgrade group."""

    id_: str | None = Field(default=None, alias="id")
    name: str | None = None
    description: str | None = None


class NetworksStagesMilestones(_BaseSchema):
    """The Staged Upgrade Milestones for the stage."""

    scheduled_for: str | None = Field(default=None, alias="scheduledFor")
    started_at: str | None = Field(default=None, alias="startedAt")
    completed_at: str | None = Field(default=None, alias="completedAt")
    canceled_at: str | None = Field(default=None, alias="canceledAt")


class NetworksDevicesItem(_BaseSchema):
    """Schema for NetworksDevicesItem."""

    serial: str | None = None
    name: str | None = None


class NetworksSwitchStacksItem(_BaseSchema):
    """Schema for NetworksSwitchStacksItem."""

    id_: str | None = Field(default=None, alias="id")
    name: str | None = None


class NetworksCenter(_BaseSchema):
    """The longitude and latitude of the center of your floor plan. The 'center' or two adjacent
    corners (e.g. 'topLeftCorner' and 'bottomLeftCorner') must be specified. If 'center' is
    specified, the floor plan is placed over that point with no rotation. If two adjacent
    corners are specified, the floor plan is rotated to line up with the two specified points.
    The aspect ratio of the floor plan's image is preserved regardless of which corners/center
    are specified. (This means if that more than two corners are specified, only two corners may
    be used to preserve the floor plan's aspect ratio.). No two points can have the same
    latitude, longitude pair.
    """

    lat: float | None = None
    lng: float | None = None


class NetworksJobsCompleted(_BaseSchema):
    """Auto locate job progress information."""

    percentage: int | None = None


class NetworksJobsErrorsItem(_BaseSchema):
    """Schema for NetworksJobsErrorsItem."""

    source: str | None = None
    type_: str | None = Field(default=None, alias="type")


class PublishNetworkFloorPlansAutoLocateJobResponse(_BaseSchema):
    """Update the status of a finished auto locate job to be published, and update device
    locations.
    """

    success: bool | None = None


class RecalculateNetworkFloorPlansAutoLocateJobResponse(_BaseSchema):
    """Trigger auto locate recalculation for a job, and optionally set anchors."""

    success: bool | None = None


class BatchNetworkFloorPlansDevicesUpdateResponse(_BaseSchema):
    """Update floorplan assignments for a batch of devices."""

    success: bool | None = None


class NetworksMonday(_BaseSchema):
    """The schedule object for Monday."""

    active: bool | None = None
    from_: str | None = Field(default=None, alias="from")
    to: str | None = None


class NetworksBandwidthLimits(_BaseSchema):
    """The bandwidth limits object, specifying upload and download speed for clients bound to the
    group policy. These are only enforced if 'settings' is set to 'custom'.
    """

    limit_up: int | None = Field(default=None, alias="limitUp")
    limit_down: int | None = Field(default=None, alias="limitDown")


class NetworksDefinitionsItem(_BaseSchema):
    """Schema for NetworksDefinitionsItem."""

    type_: str = Field(alias="type")
    value: str


class NetworksL3FirewallRulesItem(_BaseSchema):
    """Schema for NetworksL3FirewallRulesItem."""

    comment: str | None = None
    policy: str
    protocol: str
    dest_port: str | None = Field(default=None, alias="destPort")
    dest_cidr: str = Field(alias="destCidr")


class NetworksL7FirewallRulesItem(_BaseSchema):
    """Schema for NetworksL7FirewallRulesItem."""

    policy: str | None = None
    type_: str | None = Field(default=None, alias="type")
    value: str | None = None


class NetworksAllowedUrlPatterns(_BaseSchema):
    """Settings for allowed URL patterns."""

    settings: str | None = None
    patterns: list[str] | None = None


class NetworksBlockedUrlCategories(_BaseSchema):
    """Settings for blocked URL categories."""

    settings: str | None = None
    categories: list[str] | None = None


class NetworksVlanTagging(_BaseSchema):
    """The VLAN tagging settings for your group policy. Only available if your network has a
    wireless configuration.
    """

    settings: str | None = None
    vlan_id: str | None = Field(default=None, alias="vlanId")


class NetworksRulesItem(_BaseSchema):
    """Schema for NetworksRulesItem."""

    description: str | None = None
    vlan_id: str = Field(alias="vlanId")
    services: list[str]


class NetworksLldp(_BaseSchema):
    """Lldp information."""

    port_id: str | None = Field(default=None, alias="portId")


class NetworksClientsItem(_BaseSchema):
    """Schema for NetworksClientsItem."""

    mac: str | None = None


class NetworksApplicationsItem(_BaseSchema):
    """Schema for NetworksApplicationsItem."""

    url: str | None = None
    name: str | None = None


class NetworksAuthorizationsItem(_BaseSchema):
    """Schema for NetworksAuthorizationsItem."""

    ssid_number: int | None = Field(default=None, alias="ssidNumber")
    authorized_zone: str | None = Field(default=None, alias="authorizedZone")
    expires_at: str | None = Field(default=None, alias="expiresAt")
    authorized_by_name: str | None = Field(default=None, alias="authorizedByName")
    authorized_by_email: str | None = Field(default=None, alias="authorizedByEmail")


class NetworksTls(_BaseSchema):
    """TLS settings of the MQTT broker."""

    has_ca_certificate: bool | None = Field(default=None, alias="hasCaCertificate")
    verify_hostnames: bool | None = Field(default=None, alias="verifyHostnames")


class NetworksAuthentication(_BaseSchema):
    """Authentication settings of the MQTT broker."""

    username: str | None = None


class GetNetworkNetflowResponse(_BaseSchema):
    """Return the NetFlow traffic reporting settings for a network."""

    reporting_enabled: bool | None = Field(default=None, alias="reportingEnabled")
    collector_ip: str | None = Field(default=None, alias="collectorIp")
    collector_port: int | None = Field(default=None, alias="collectorPort")
    eta_enabled: bool | None = Field(default=None, alias="etaEnabled")
    eta_dst_port: int | None = Field(default=None, alias="etaDstPort")


class UpdateNetworkNetflowResponse(_BaseSchema):
    """Update the NetFlow traffic reporting settings for a network."""

    reporting_enabled: bool | None = Field(default=None, alias="reportingEnabled")
    collector_ip: str | None = Field(default=None, alias="collectorIp")
    collector_port: int | None = Field(default=None, alias="collectorPort")
    eta_enabled: bool | None = Field(default=None, alias="etaEnabled")
    eta_dst_port: int | None = Field(default=None, alias="etaDstPort")


class NetworksWifi0Item(_BaseSchema):
    """Schema for NetworksWifi0Item."""

    start_time: str | None = Field(default=None, alias="startTime")
    end_time: str | None = Field(default=None, alias="endTime")
    utilization_total: float | None = Field(default=None, alias="utilizationTotal")
    utilization80211: float | None = None
    utilization_non80211: float | None = Field(default=None, alias="utilizationNon80211")


class GetNetworkPiiPiiKeysResponse(_BaseSchema):
    """List the keys required to access Personally Identifiable Information (PII) for a given
    identifier. Exactly one identifier will be accepted. If the organization contains org-wide
    Systems Manager users matching the key provided then there will be an entry with the key "0"
    containing the applicable keys. ## ALTERNATE PATH ```
    /organizations/{organizationId}/pii/piiKeys ```.
    """


class GetNetworkPiiRequestsResponseItem(_BaseSchema):
    """Schema for GetNetworkPiiRequestsResponseItem."""

    id_: str | None = Field(default=None, alias="id")
    organization_wide: bool | None = Field(default=None, alias="organizationWide")
    network_id: str | None = Field(default=None, alias="networkId")
    type_: str | None = Field(default=None, alias="type")
    mac: str | None = None
    datasets: str | None = None
    status: str | None = None
    created_at: int | None = Field(default=None, alias="createdAt")
    completed_at: int | None = Field(default=None, alias="completedAt")


class CreateNetworkPiiRequestResponse(_BaseSchema):
    """Submit a new delete or restrict processing PII request ## ALTERNATE PATH ```
    /organizations/{organizationId}/pii/requests ```.
    """

    id_: str | None = Field(default=None, alias="id")
    organization_wide: bool | None = Field(default=None, alias="organizationWide")
    network_id: str | None = Field(default=None, alias="networkId")
    type_: str | None = Field(default=None, alias="type")
    mac: str | None = None
    datasets: str | None = None
    status: str | None = None
    created_at: int | None = Field(default=None, alias="createdAt")
    completed_at: int | None = Field(default=None, alias="completedAt")


class GetNetworkPiiRequestResponse(_BaseSchema):
    """Return a PII request ## ALTERNATE PATH ```
    /organizations/{organizationId}/pii/requests/{requestId} ```.
    """

    id_: str | None = Field(default=None, alias="id")
    organization_wide: bool | None = Field(default=None, alias="organizationWide")
    network_id: str | None = Field(default=None, alias="networkId")
    type_: str | None = Field(default=None, alias="type")
    mac: str | None = None
    datasets: str | None = None
    status: str | None = None
    created_at: int | None = Field(default=None, alias="createdAt")
    completed_at: int | None = Field(default=None, alias="completedAt")


class GetNetworkPiiSmDevicesForKeyResponse(_BaseSchema):
    """Given a piece of Personally Identifiable Information (PII), return the Systems Manager
    device ID(s) associated with that identifier. These device IDs can be used with the Systems
    Manager API endpoints to retrieve device details. Exactly one identifier will be accepted.
    ## ALTERNATE PATH ``` /organizations/{organizationId}/pii/smDevicesForKey ```.
    """


class GetNetworkPiiSmOwnersForKeyResponse(_BaseSchema):
    """Given a piece of Personally Identifiable Information (PII), return the Systems Manager owner
    ID(s) associated with that identifier. These owner IDs can be used with the Systems Manager
    API endpoints to retrieve owner details. Exactly one identifier will be accepted. ##
    ALTERNATE PATH ``` /organizations/{organizationId}/pii/smOwnersForKey ```.
    """


class NetworksSsidItem(_BaseSchema):
    """Schema for NetworksSsidItem."""

    ssid_number: int | None = Field(default=None, alias="ssidNumber")


class NetworksLocalStatusPageAuthentication(_BaseSchema):
    """A hash of Local Status page(s)' authentication options applied to the Network."""

    enabled: bool | None = None
    username: str | None = None


class GetNetworkSettingsResponseNamedVlans(_BaseSchema):
    """A hash of Named VLANs options applied to the Network."""

    enabled: bool


class GetNetworkSnmpResponseUsersItem(_BaseSchema):
    """Schema for GetNetworkSnmpResponseUsersItem."""

    username: str | None = None
    passphrase: str | None = None


class GetNetworkSplashLoginAttemptsResponseItem(_BaseSchema):
    """Schema for GetNetworkSplashLoginAttemptsResponseItem."""

    name: str | None = None
    login: str | None = None
    ssid: str | None = None
    login_at: str | None = Field(default=None, alias="loginAt")
    gateway_device_mac: str | None = Field(default=None, alias="gatewayDeviceMac")
    client_mac: str | None = Field(default=None, alias="clientMac")
    client_id: str | None = Field(default=None, alias="clientId")
    authorization: str | None = None


class SplitNetworkResponseResultingNetworksItem(_BaseSchema):
    """Schema for SplitNetworkResponseResultingNetworksItem."""

    id_: str | None = Field(default=None, alias="id")
    organization_id: str | None = Field(default=None, alias="organizationId")
    name: str | None = None
    product_types: list[str] | None = Field(default=None, alias="productTypes")
    time_zone: str | None = Field(default=None, alias="timeZone")
    tags: list[str] | None = None
    enrollment_string: str | None = Field(default=None, alias="enrollmentString")
    url: str | None = None
    notes: str | None = None
    is_bound_to_config_template: bool | None = Field(default=None, alias="isBoundToConfigTemplate")


class GetNetworkSyslogServersResponseServersItem(_BaseSchema):
    """Schema for GetNetworkSyslogServersResponseServersItem."""

    host: str | None = None
    port: int | None = None
    roles: list[str] | None = None


class NetworksCounts(_BaseSchema):
    """Client counts."""

    total: int | None = None


class NetworksUplinksItem(_BaseSchema):
    """Schema for NetworksUplinksItem."""

    vlan_id: int | None = Field(default=None, alias="vlanId")


class NetworksLldp2(_BaseSchema):
    """LLDP information."""

    chassis_id: str | None = Field(default=None, alias="chassisId")
    system_name: str | None = Field(default=None, alias="systemName")
    system_description: str | None = Field(default=None, alias="systemDescription")
    system_capabilities: list[str] | None = Field(default=None, alias="systemCapabilities")
    management_address: str | None = Field(default=None, alias="managementAddress")


class NetworksCdp(_BaseSchema):
    """CDP information."""

    platform: str | None = None
    device_id: str | None = Field(default=None, alias="deviceId")
    address: str | None = None
    capabilities: list[str] | None = None
    management_address: str | None = Field(default=None, alias="managementAddress")


class NetworksNode(_BaseSchema):
    """Node reference."""

    derived_id: str | None = Field(default=None, alias="derivedId")
    type_: str | None = Field(default=None, alias="type")


class NetworksLldp3(_BaseSchema):
    """LLDP port information."""

    port_id: str | None = Field(default=None, alias="portId")
    port_description: str | None = Field(default=None, alias="portDescription")


class NetworksCdp2(_BaseSchema):
    """CDP port information."""

    port_id: str | None = Field(default=None, alias="portId")
    native_vlan: int | None = Field(default=None, alias="nativeVlan")


class GetNetworkTrafficResponseItem(_BaseSchema):
    """Schema for GetNetworkTrafficResponseItem."""

    application: str | None = None
    destination: str | None = None
    protocol: str | None = None
    port: int | None = None
    sent: float | None = None
    recv: float | None = None
    num_clients: int | None = Field(default=None, alias="numClients")
    active_time: int | None = Field(default=None, alias="activeTime")
    flows: int | None = None


class GetNetworkTrafficAnalysisResponseCustomPieChartItemsItem(_BaseSchema):
    """Schema for GetNetworkTrafficAnalysisResponseCustomPieChartItemsItem."""

    name: str
    type_: str = Field(alias="type")
    value: str


class GetNetworkTrafficShapingDscpTaggingOptionsResponse(RootModel[list[dict[str, Any]]]):
    """Returns the available DSCP tagging options for your traffic shaping rules."""


class UnbindNetworkResponse(_BaseSchema):
    """Unbind a network from a template."""

    id_: str | None = Field(default=None, alias="id")
    organization_id: str | None = Field(default=None, alias="organizationId")
    name: str | None = None
    product_types: list[str] | None = Field(default=None, alias="productTypes")
    time_zone: str | None = Field(default=None, alias="timeZone")
    tags: list[str] | None = None
    enrollment_string: str | None = Field(default=None, alias="enrollmentString")
    url: str | None = None
    notes: str | None = None
    is_bound_to_config_template: bool | None = Field(default=None, alias="isBoundToConfigTemplate")


class NetworksVlanGroupsItem(_BaseSchema):
    """Schema for NetworksVlanGroupsItem."""

    name: str | None = None
    vlan_ids: str | None = Field(default=None, alias="vlanIds")


class NetworksVlanProfile(_BaseSchema):
    """The VLAN Profile."""

    iname: str | None = None
    name: str | None = None
    is_default: bool | None = Field(default=None, alias="isDefault")


class NetworksStack(_BaseSchema):
    """The Switch Stack the device belongs to."""

    id_: str | None = Field(default=None, alias="id")


class ReassignNetworkVlanProfilesAssignmentsResponseVlanProfile(_BaseSchema):
    """The VLAN Profile."""

    iname: str | None = None
    name: str | None = None


class NetworksPayloadTemplate(_BaseSchema):
    """The payload template to use when posting data to the HTTP server."""

    payload_template_id: str | None = Field(default=None, alias="payloadTemplateId")
    name: str | None = None


class NetworksHeadersItem(_BaseSchema):
    """Schema for NetworksHeadersItem."""

    name: str | None = None
    template: str | None = None


class NetworksByNetwork(_BaseSchema):
    """Information on network access to the template."""

    admins_can_modify: bool | None = Field(default=None, alias="adminsCanModify")


class CreateNetworkWebhooksWebhookTestResponse(_BaseSchema):
    """Send a test webhook for a network."""

    id_: str | None = Field(default=None, alias="id")
    url: str | None = None
    status: str | None = None


class GetNetworkWebhooksWebhookTestResponse(_BaseSchema):
    """Return the status of a webhook test for a network."""

    id_: str | None = Field(default=None, alias="id")
    url: str | None = None
    status: str | None = None


class NetworksDestinations(_BaseSchema):
    """the destinations this alert is configured to be delivered to."""

    email: NetworksEmail | None = None
    push: NetworksEmail | None = None
    sms: NetworksEmail | None = None
    webhook: NetworksEmail | None = None


class NetworksAlertsFilters(_BaseSchema):
    """A hash of specific configuration data for the alert. Only filters specific to the alert will
    be updated.
    """

    conditions: list[NetworksConditionsItem] | None = None
    failure_type: str | None = Field(default=None, alias="failureType")
    lookback_window: int | None = Field(default=None, alias="lookbackWindow")
    min_duration: int | None = Field(default=None, alias="minDuration")
    name: str | None = None
    period: int | None = None
    priority: str | None = None
    regex: str | None = None
    selector: str | None = None
    serials: list[str] | None = None
    ssid_num: int | None = Field(default=None, alias="ssidNum")
    tag: str | None = None
    threshold: int | None = None
    timeout: int | None = None


class GetNetworkAlertsSettingsResponseMuting(_BaseSchema):
    """Mute alerts under certain conditions."""

    by_port_schedules: NetworksMutingByPortSchedules | None = Field(
        default=None, alias="byPortSchedules"
    )


class GetNetworkBluetoothClientsResponse(RootModel[list[GetNetworkBluetoothClientsResponseItem]]):
    """List the Bluetooth clients seen by APs in this network."""


class GetNetworkClientsResponseItem(_BaseSchema):
    """Schema for GetNetworkClientsResponseItem."""

    id_: str | None = Field(default=None, alias="id")
    mac: str | None = None
    ip: str | None = None
    ip6: str | None = None
    description: str | None = None
    first_seen: int | None = Field(default=None, alias="firstSeen")
    last_seen: int | None = Field(default=None, alias="lastSeen")
    manufacturer: str | None = None
    os: str | None = None
    user: str | None = None
    vlan: str | None = None
    ssid: str | None = None
    switchport: str | None = None
    wireless_capabilities: str | None = Field(default=None, alias="wirelessCapabilities")
    sm_installed: bool | None = Field(default=None, alias="smInstalled")
    recent_device_mac: str | None = Field(default=None, alias="recentDeviceMac")
    status: str | None = None
    usage: NetworksUsage | None = None
    named_vlan: str | None = Field(default=None, alias="namedVlan")
    adaptive_policy_group: str | None = Field(default=None, alias="adaptivePolicyGroup")
    device_type_prediction: str | None = Field(default=None, alias="deviceTypePrediction")
    recent_device_serial: str | None = Field(default=None, alias="recentDeviceSerial")
    recent_device_name: str | None = Field(default=None, alias="recentDeviceName")
    recent_device_connection: str | None = Field(default=None, alias="recentDeviceConnection")
    notes: str | None = None
    ip6_local: str | None = Field(default=None, alias="ip6Local")
    group_policy8021x: str | None = Field(default=None, alias="groupPolicy8021x")
    psk_group: str | None = Field(default=None, alias="pskGroup")


class GetNetworkClientsApplicationUsageResponseItem(_BaseSchema):
    """Schema for GetNetworkClientsApplicationUsageResponseItem."""

    client_id: str | None = Field(default=None, alias="clientId")
    client_ip: str | None = Field(default=None, alias="clientIp")
    client_mac: str | None = Field(default=None, alias="clientMac")
    application_usage: list[NetworksApplicationUsageItem] | None = Field(
        default=None, alias="applicationUsage"
    )


class GetNetworkClientsBandwidthUsageHistoryResponse(
    RootModel[list[GetNetworkClientsBandwidthUsageHistoryResponseItem]]
):
    """Returns a timeseries of total traffic consumption rates for all clients on a network within
    a given timespan, in megabits per second.
    """


class GetNetworkClientsOverviewResponse(_BaseSchema):
    """Return overview statistics for network clients."""

    counts: GetNetworkClientsOverviewResponseCounts | None = None
    usages: GetNetworkClientsOverviewResponseUsages | None = None


class ProvisionNetworkClientsResponse(_BaseSchema):
    """Provisions a client with a name and policy. Clients can be provisioned before they associate
    to the network.
    """

    clients: list[ProvisionNetworkClientsResponseClientsItem] | None = None
    device_policy: str | None = Field(default=None, alias="devicePolicy")
    group_policy_id: str | None = Field(default=None, alias="groupPolicyId")


class GetNetworkClientsUsageHistoriesResponseItem(_BaseSchema):
    """Schema for GetNetworkClientsUsageHistoriesResponseItem."""

    client_id: str | None = Field(default=None, alias="clientId")
    client_ip: str | None = Field(default=None, alias="clientIp")
    client_mac: str | None = Field(default=None, alias="clientMac")
    usage_history: list[NetworksUsageHistoryItem] | None = Field(default=None, alias="usageHistory")


class GetNetworkClientResponse(_BaseSchema):
    """Return the client associated with the given identifier. Clients can be identified by a
    client key or either the MAC or IP depending on whether the network uses Track-by-IP.
    """

    id_: str | None = Field(default=None, alias="id")
    mac: str | None = None
    ip: str | None = None
    ip6: str | None = None
    ip6_local: str | None = Field(default=None, alias="ip6Local")
    description: str | None = None
    first_seen: int | None = Field(default=None, alias="firstSeen")
    last_seen: int | None = Field(default=None, alias="lastSeen")
    manufacturer: str | None = None
    os: str | None = None
    user: str | None = None
    vlan: str | None = None
    named_vlan: str | None = Field(default=None, alias="namedVlan")
    ssid: str | None = None
    switchport: str | None = None
    wireless_capabilities: str | None = Field(default=None, alias="wirelessCapabilities")
    sm_installed: bool | None = Field(default=None, alias="smInstalled")
    recent_device_mac: str | None = Field(default=None, alias="recentDeviceMac")
    recent_device_name: str | None = Field(default=None, alias="recentDeviceName")
    recent_device_serial: str | None = Field(default=None, alias="recentDeviceSerial")
    recent_device_connection: str | None = Field(default=None, alias="recentDeviceConnection")
    client_vpn_connections: list[GetNetworkClientResponseClientVpnConnectionsItem] | None = Field(
        default=None, alias="clientVpnConnections"
    )
    lldp: list[list[str]] | None = None
    cdp: list[list[str]] | None = None
    status: str | None = None
    notes: str | None = None
    device_type_prediction: str | None = Field(default=None, alias="deviceTypePrediction")


class GetNetworkClientPolicyResponse(_BaseSchema):
    """Return the policy assigned to a client on the network. Clients can be identified by a client
    key or either the MAC or IP depending on whether the network uses Track-by-IP.
    """

    mac: str | None = None
    device_policy: str | None = Field(default=None, alias="devicePolicy")
    group_policy_id: str | None = Field(default=None, alias="groupPolicyId")
    policies_by_ssid: list[GetNetworkClientPolicyResponsePoliciesBySsidItem] | None = Field(
        default=None, alias="policiesBySsid"
    )


class UpdateNetworkClientPolicyResponse(_BaseSchema):
    """Update the policy assigned to a client on the network. Clients can be identified by a client
    key or either the MAC or IP depending on whether the network uses Track-by-IP.
    """

    mac: str | None = None
    device_policy: str | None = Field(default=None, alias="devicePolicy")
    group_policy_id: str | None = Field(default=None, alias="groupPolicyId")
    policies_by_ssid: list[GetNetworkClientPolicyResponsePoliciesBySsidItem] | None = Field(
        default=None, alias="policiesBySsid"
    )


class GetNetworkClientTrafficHistoryResponse(
    RootModel[list[GetNetworkClientTrafficHistoryResponseItem]]
):
    """Return the client's network traffic data over time. Usage data is in kilobytes. This
    endpoint requires detailed traffic analysis to be enabled on the Network-wide > General
    page. Clients can be identified by a client key or either the MAC or IP depending on whether
    the network uses Track-by-IP.
    """


class GetNetworkClientUsageHistoryResponse(
    RootModel[list[GetNetworkClientUsageHistoryResponseItem]]
):
    """Return the client's daily usage history. Usage data is in kilobytes. Clients can be
    identified by a client key or either the MAC or IP depending on whether the network uses
    Track-by-IP.
    """


class VmxNetworkDevicesClaimResponse(_BaseSchema):
    """Claim a vMX into a network."""

    name: str | None = None
    lat: float | None = None
    lng: float | None = None
    address: str | None = None
    notes: str | None = None
    tags: list[str] | None = None
    network_id: str | None = Field(default=None, alias="networkId")
    serial: str | None = None
    model: str | None = None
    imei: str | None = None
    mac: str | None = None
    lan_ip: str | None = Field(default=None, alias="lanIp")
    firmware: str | None = None
    product_type: str | None = Field(default=None, alias="productType")
    details: list[NetworksDetailsItem] | None = None


class NetworksDevicesItem2(_BaseSchema):
    """Schema for NetworksDevicesItem2."""

    name: str | None = None
    lat: float | None = None
    lng: float | None = None
    address: str | None = None
    notes: str | None = None
    tags: list[str] | None = None
    network_id: str | None = Field(default=None, alias="networkId")
    serial: str | None = None
    model: str | None = None
    imei: str | None = None
    mac: str | None = None
    lan_ip: str | None = Field(default=None, alias="lanIp")
    firmware: str | None = None
    product_type: str | None = Field(default=None, alias="productType")
    details: list[NetworksDetailsItem] | None = None


class GetNetworkDevicesResponseItem(_BaseSchema):
    """Schema for GetNetworkDevicesResponseItem."""

    name: str | None = None
    lat: float | None = None
    lng: float | None = None
    address: str | None = None
    notes: str | None = None
    tags: list[str] | None = None
    network_id: str | None = Field(default=None, alias="networkId")
    serial: str | None = None
    model: str | None = None
    mac: str | None = None
    lan_ip: str | None = Field(default=None, alias="lanIp")
    firmware: str | None = None
    floor_plan_id: str | None = Field(default=None, alias="floorPlanId")
    details: list[NetworksDetailsItem] | None = None
    beacon_id_params: NetworksBeaconIdParams | None = Field(default=None, alias="beaconIdParams")


class ClaimNetworkDevicesResponse(_BaseSchema):
    """Claim devices into a network. (Note: for recently claimed devices, it may take a few minutes
    for API requests against that device to succeed). This operation can be used up to ten times
    within a single five minute window.
    """

    serials: list[str] | None = None
    errors: list[ClaimNetworkDevicesResponseErrorsItem] | None = None


class GetNetworkEventsResponseEventsItem(_BaseSchema):
    """Schema for GetNetworkEventsResponseEventsItem."""

    occurred_at: str | None = Field(default=None, alias="occurredAt")
    network_id: str | None = Field(default=None, alias="networkId")
    type_: str | None = Field(default=None, alias="type")
    description: str | None = None
    category: str | None = None
    client_id: str | None = Field(default=None, alias="clientId")
    client_description: str | None = Field(default=None, alias="clientDescription")
    client_mac: str | None = Field(default=None, alias="clientMac")
    device_serial: str | None = Field(default=None, alias="deviceSerial")
    device_name: str | None = Field(default=None, alias="deviceName")
    ssid_number: int | None = Field(default=None, alias="ssidNumber")
    event_data: NetworksEventsEventData | None = Field(default=None, alias="eventData")


class GetNetworkEventsEventTypesResponse(RootModel[list[GetNetworkEventsEventTypesResponseItem]]):
    """List the event type to human-readable description."""


class NetworksLastUpgrade(_BaseSchema):
    """Details of the last firmware upgrade on the device."""

    time: str | None = None
    from_version: NetworksCurrentVersion | None = Field(default=None, alias="fromVersion")
    to_version: NetworksCurrentVersion | None = Field(default=None, alias="toVersion")


class NetworksNextUpgrade(_BaseSchema):
    """Details of the next firmware upgrade on the device."""

    time: str | None = None
    to_version: NetworksCurrentVersion | None = Field(default=None, alias="toVersion")


class CreateNetworkFirmwareUpgradesRollbackResponse(_BaseSchema):
    """Rollback a Firmware Upgrade For A Network."""

    product: str | None = None
    status: str | None = None
    upgrade_batch_id: str | None = Field(default=None, alias="upgradeBatchId")
    time: str | None = None
    to_version: NetworksCurrentVersion | None = Field(default=None, alias="toVersion")
    reasons: list[CreateNetworkFirmwareUpgradesRollbackResponseReasonsItem] | None = None


class NetworksNextUpgrade2(_BaseSchema):
    """Details of the next firmware upgrade."""

    to_version: NetworksToVersion | None = Field(default=None, alias="toVersion")


class GetNetworkFirmwareUpgradesStagedStagesResponseItem(_BaseSchema):
    """Schema for GetNetworkFirmwareUpgradesStagedStagesResponseItem."""

    group: NetworksStagesGroup | None = None


class UpdateNetworkFirmwareUpgradesStagedStagesResponseItem(_BaseSchema):
    """Schema for UpdateNetworkFirmwareUpgradesStagedStagesResponseItem."""

    group: NetworksStagesGroup | None = None


class GetNetworkFirmwareUpgradesStagedEventsResponseStagesItem(_BaseSchema):
    """Schema for GetNetworkFirmwareUpgradesStagedEventsResponseStagesItem."""

    group: NetworksStagesGroup | None = None
    milestones: NetworksStagesMilestones | None = None
    status: str | None = None


class NetworksAssignedDevices(_BaseSchema):
    """The devices and Switch Stacks assigned to the Group."""

    devices: list[NetworksDevicesItem] | None = None
    switch_stacks: list[NetworksSwitchStacksItem] | None = Field(default=None, alias="switchStacks")


class NetworksPeersItem(_BaseSchema):
    """Schema for NetworksPeersItem."""

    url: str | None = None
    network: NetworksSwitchStacksItem | None = None


class NetworksVlanNamesItem(_BaseSchema):
    """Schema for NetworksVlanNamesItem."""

    name: str | None = None
    vlan_id: str | None = Field(default=None, alias="vlanId")
    adaptive_policy_group: NetworksSwitchStacksItem | None = Field(
        default=None, alias="adaptivePolicyGroup"
    )


class NetworksJobsRanging(_BaseSchema):
    """Ranging status and progress information."""

    status: str | None = None
    completed: NetworksJobsCompleted | None = None


class NetworksScheduling(_BaseSchema):
    """The schedule for the group policy. Schedules are applied to days of the week."""

    enabled: bool | None = None
    monday: NetworksMonday | None = None
    tuesday: NetworksMonday | None = None
    wednesday: NetworksMonday | None = None
    thursday: NetworksMonday | None = None
    friday: NetworksMonday | None = None
    saturday: NetworksMonday | None = None
    sunday: NetworksMonday | None = None


class NetworksBandwidth(_BaseSchema):
    """The bandwidth settings for clients bound to your group policy."""

    settings: str | None = None
    bandwidth_limits: NetworksBandwidthLimits | None = Field(default=None, alias="bandwidthLimits")


class NetworksContentFiltering(_BaseSchema):
    """The content filtering settings for your group policy."""

    allowed_url_patterns: NetworksAllowedUrlPatterns | None = Field(
        default=None, alias="allowedUrlPatterns"
    )
    blocked_url_patterns: NetworksAllowedUrlPatterns | None = Field(
        default=None, alias="blockedUrlPatterns"
    )
    blocked_url_categories: NetworksBlockedUrlCategories | None = Field(
        default=None, alias="blockedUrlCategories"
    )


class NetworksBonjourForwarding(_BaseSchema):
    """The Bonjour settings for your group policy. Only valid if your network has a wireless
    configuration.
    """

    settings: str | None = None
    rules: list[NetworksRulesItem] | None = None


class NetworksDevicesItem3(_BaseSchema):
    """Schema for NetworksDevicesItem3."""

    url: str | None = None
    name: str | None = None
    product_type: str | None = Field(default=None, alias="productType")
    serial: str | None = None
    mac: str | None = None
    lldp: NetworksLldp | None = None
    clients: list[NetworksClientsItem] | None = None


class GetNetworkMerakiAuthUsersResponseItem(_BaseSchema):
    """Schema for GetNetworkMerakiAuthUsersResponseItem."""

    id_: str | None = Field(default=None, alias="id")
    email: str | None = None
    name: str | None = None
    created_at: str | None = Field(default=None, alias="createdAt")
    account_type: str | None = Field(default=None, alias="accountType")
    is_admin: bool | None = Field(default=None, alias="isAdmin")
    authorizations: list[NetworksAuthorizationsItem] | None = None


class CreateNetworkMerakiAuthUserResponse(_BaseSchema):
    """Authorize a user configured with Meraki Authentication for a network (currently supports
    802.1X, splash guest, and client VPN users, and currently, organizations have a 50,000 user
    cap).
    """

    id_: str | None = Field(default=None, alias="id")
    email: str | None = None
    name: str | None = None
    created_at: str | None = Field(default=None, alias="createdAt")
    account_type: str | None = Field(default=None, alias="accountType")
    is_admin: bool | None = Field(default=None, alias="isAdmin")
    authorizations: list[NetworksAuthorizationsItem] | None = None


class GetNetworkMerakiAuthUserResponse(_BaseSchema):
    """Return the Meraki Auth splash guest, RADIUS, or client VPN user."""

    id_: str | None = Field(default=None, alias="id")
    email: str | None = None
    name: str | None = None
    created_at: str | None = Field(default=None, alias="createdAt")
    account_type: str | None = Field(default=None, alias="accountType")
    is_admin: bool | None = Field(default=None, alias="isAdmin")
    authorizations: list[NetworksAuthorizationsItem] | None = None


class UpdateNetworkMerakiAuthUserResponse(_BaseSchema):
    """Update a user configured with Meraki Authentication (currently, 802.1X RADIUS, splash guest,
    and client VPN users can be updated).
    """

    id_: str | None = Field(default=None, alias="id")
    email: str | None = None
    name: str | None = None
    created_at: str | None = Field(default=None, alias="createdAt")
    account_type: str | None = Field(default=None, alias="accountType")
    is_admin: bool | None = Field(default=None, alias="isAdmin")
    authorizations: list[NetworksAuthorizationsItem] | None = None


class NetworksSecurity(_BaseSchema):
    """Security settings of the MQTT broker."""

    mode: str | None = None
    tls: NetworksTls | None = None


class GetNetworkNetworkHealthChannelUtilizationResponseItem(_BaseSchema):
    """Schema for GetNetworkNetworkHealthChannelUtilizationResponseItem."""

    serial: str | None = None
    model: str | None = None
    tags: str | None = None
    wifi0: list[NetworksWifi0Item] | None = None
    wifi1: list[NetworksWifi0Item] | None = None


class GetNetworkPiiRequestsResponse(RootModel[list[GetNetworkPiiRequestsResponseItem]]):
    """List the PII requests for this network or organization ## ALTERNATE PATH ```
    /organizations/{organizationId}/pii/requests ```.
    """


class NetworksAssignedItem(_BaseSchema):
    """Schema for NetworksAssignedItem."""

    name: str | None = None
    type_: str | None = Field(default=None, alias="type")
    group_policy_id: str | None = Field(default=None, alias="groupPolicyId")
    ssid: list[NetworksSsidItem] | None = None


class GetNetworkSettingsResponseLocalStatusPage(_BaseSchema):
    """A hash of Local Status page(s)' authentication options applied to the Network."""

    authentication: NetworksLocalStatusPageAuthentication | None = None


class GetNetworkSnmpResponse(_BaseSchema):
    """Return the SNMP settings for a network."""

    access: str | None = None
    community_string: str | None = Field(default=None, alias="communityString")
    users: list[GetNetworkSnmpResponseUsersItem] | None = None


class UpdateNetworkSnmpResponse(_BaseSchema):
    """Update the SNMP settings for a network."""

    access: str | None = None
    community_string: str | None = Field(default=None, alias="communityString")
    users: list[GetNetworkSnmpResponseUsersItem] | None = None


class GetNetworkSplashLoginAttemptsResponse(
    RootModel[list[GetNetworkSplashLoginAttemptsResponseItem]]
):
    """List the splash login attempts for a network."""


class SplitNetworkResponse(_BaseSchema):
    """Split a combined network into individual networks for each type of device."""

    resulting_networks: list[SplitNetworkResponseResultingNetworksItem] | None = Field(
        default=None, alias="resultingNetworks"
    )


class GetNetworkSyslogServersResponse(_BaseSchema):
    """List the syslog servers for a network."""

    servers: list[GetNetworkSyslogServersResponseServersItem] | None = None


class UpdateNetworkSyslogServersResponse(_BaseSchema):
    """Update the syslog servers for a network."""

    servers: list[GetNetworkSyslogServersResponseServersItem] | None = None


class NetworksClients(_BaseSchema):
    """Client information."""

    counts: NetworksCounts | None = None


class NetworksNodesDiscovered(_BaseSchema):
    """Discovered device information (present when type is 'discovered')."""

    lldp: NetworksLldp2 | None = None
    cdp: NetworksCdp | None = None


class NetworksDiscovered(_BaseSchema):
    """Discovered LLDP/CDP information at this end."""

    lldp: NetworksLldp3 | None = None
    cdp: NetworksCdp2 | None = None


class GetNetworkTrafficResponse(RootModel[list[GetNetworkTrafficResponseItem]]):
    """Return the traffic analysis data for this network. Traffic analysis with hostname visibility
    must be enabled on the network.
    """


class GetNetworkTrafficAnalysisResponse(_BaseSchema):
    """Return the traffic analysis settings for a network."""

    mode: str | None = None
    custom_pie_chart_items: (
        list[GetNetworkTrafficAnalysisResponseCustomPieChartItemsItem] | None
    ) = Field(default=None, alias="customPieChartItems")


class UpdateNetworkTrafficAnalysisResponse(_BaseSchema):
    """Update the traffic analysis settings for a network."""

    mode: str | None = None
    custom_pie_chart_items: (
        list[GetNetworkTrafficAnalysisResponseCustomPieChartItemsItem] | None
    ) = Field(default=None, alias="customPieChartItems")


class GetNetworkVlanProfilesAssignmentsByDeviceResponseItem(_BaseSchema):
    """Schema for GetNetworkVlanProfilesAssignmentsByDeviceResponseItem."""

    name: str | None = None
    serial: str | None = None
    mac: str | None = None
    product_type: str | None = Field(default=None, alias="productType")
    vlan_profile: NetworksVlanProfile | None = Field(default=None, alias="vlanProfile")
    stack: NetworksStack | None = None


class ReassignNetworkVlanProfilesAssignmentsResponse(_BaseSchema):
    """Update the assigned VLAN Profile for devices in a network."""

    vlan_profile: ReassignNetworkVlanProfilesAssignmentsResponseVlanProfile | None = Field(
        default=None, alias="vlanProfile"
    )
    serials: list[str] | None = None
    stack_ids: list[str] | None = Field(default=None, alias="stackIds")


class GetNetworkWebhooksHttpServersResponseItem(_BaseSchema):
    """Schema for GetNetworkWebhooksHttpServersResponseItem."""

    id_: str | None = Field(default=None, alias="id")
    name: str | None = None
    url: str | None = None
    network_id: str | None = Field(default=None, alias="networkId")
    payload_template: NetworksPayloadTemplate | None = Field(default=None, alias="payloadTemplate")


class CreateNetworkWebhooksHttpServerResponse(_BaseSchema):
    """Add an HTTP server to a network."""

    id_: str | None = Field(default=None, alias="id")
    name: str | None = None
    url: str | None = None
    network_id: str | None = Field(default=None, alias="networkId")
    payload_template: NetworksPayloadTemplate | None = Field(default=None, alias="payloadTemplate")


class GetNetworkWebhooksHttpServerResponse(_BaseSchema):
    """Return an HTTP server for a network."""

    id_: str | None = Field(default=None, alias="id")
    name: str | None = None
    url: str | None = None
    network_id: str | None = Field(default=None, alias="networkId")
    payload_template: NetworksPayloadTemplate | None = Field(default=None, alias="payloadTemplate")


class UpdateNetworkWebhooksHttpServerResponse(_BaseSchema):
    """Update an HTTP server. To change a URL, create a new HTTP server."""

    id_: str | None = Field(default=None, alias="id")
    name: str | None = None
    url: str | None = None
    network_id: str | None = Field(default=None, alias="networkId")
    payload_template: NetworksPayloadTemplate | None = Field(default=None, alias="payloadTemplate")


class NetworksSharing(_BaseSchema):
    """Information on which entities have access to the template."""

    by_network: NetworksByNetwork | None = Field(default=None, alias="byNetwork")


class GetNetworkAlertsHistoryResponseItem(_BaseSchema):
    """Schema for GetNetworkAlertsHistoryResponseItem."""

    occurred_at: str | None = Field(default=None, alias="occurredAt")
    alert_type_id: str | None = Field(default=None, alias="alertTypeId")
    alert_type: str | None = Field(default=None, alias="alertType")
    device: NetworksDevice | None = None
    destinations: NetworksDestinations | None = None
    alert_data: dict[str, Any] | None = Field(default=None, alias="alertData")


class GetNetworkAlertsSettingsResponseAlertsItem(_BaseSchema):
    """Schema for GetNetworkAlertsSettingsResponseAlertsItem."""

    type_: str = Field(alias="type")
    enabled: bool | None = None
    alert_destinations: NetworksAlertsAlertDestinations | None = Field(
        default=None, alias="alertDestinations"
    )
    filters: NetworksAlertsFilters | None = None


class GetNetworkClientsResponse(RootModel[list[GetNetworkClientsResponseItem]]):
    """List the clients that have used this network in the timespan. The data is updated at most
    once every five minutes.
    """


class GetNetworkClientsApplicationUsageResponse(
    RootModel[list[GetNetworkClientsApplicationUsageResponseItem]]
):
    """Return the application usage data for clients. Usage data is in kilobytes. Clients can be
    identified by client keys or either the MACs or IPs depending on whether the network uses
    Track-by-IP.
    """


class GetNetworkClientsUsageHistoriesResponse(
    RootModel[list[GetNetworkClientsUsageHistoriesResponseItem]]
):
    """Return the usage histories for clients. Usage data is in kilobytes. Clients can be
    identified by client keys or either the MACs or IPs depending on whether the network uses
    Track-by-IP.
    """


class GetNetworkFloorPlansResponseItem(_BaseSchema):
    """Schema for GetNetworkFloorPlansResponseItem."""

    floor_plan_id: str | None = Field(default=None, alias="floorPlanId")
    image_url: str | None = Field(default=None, alias="imageUrl")
    image_url_expires_at: str | None = Field(default=None, alias="imageUrlExpiresAt")
    image_extension: str | None = Field(default=None, alias="imageExtension")
    image_md5: str | None = Field(default=None, alias="imageMd5")
    name: str | None = None
    devices: list[NetworksDevicesItem2] | None = None
    width: float | None = None
    height: float | None = None
    center: NetworksCenter | None = None
    bottom_left_corner: NetworksCenter | None = Field(default=None, alias="bottomLeftCorner")
    bottom_right_corner: NetworksCenter | None = Field(default=None, alias="bottomRightCorner")
    top_left_corner: NetworksCenter | None = Field(default=None, alias="topLeftCorner")
    top_right_corner: NetworksCenter | None = Field(default=None, alias="topRightCorner")
    floor_number: float | None = Field(default=None, alias="floorNumber")


class CreateNetworkFloorPlanResponse(_BaseSchema):
    """Upload a floor plan."""

    floor_plan_id: str | None = Field(default=None, alias="floorPlanId")
    image_url: str | None = Field(default=None, alias="imageUrl")
    image_url_expires_at: str | None = Field(default=None, alias="imageUrlExpiresAt")
    image_extension: str | None = Field(default=None, alias="imageExtension")
    image_md5: str | None = Field(default=None, alias="imageMd5")
    name: str | None = None
    devices: list[NetworksDevicesItem2] | None = None
    width: float | None = None
    height: float | None = None
    center: NetworksCenter | None = None
    bottom_left_corner: NetworksCenter | None = Field(default=None, alias="bottomLeftCorner")
    bottom_right_corner: NetworksCenter | None = Field(default=None, alias="bottomRightCorner")
    top_left_corner: NetworksCenter | None = Field(default=None, alias="topLeftCorner")
    top_right_corner: NetworksCenter | None = Field(default=None, alias="topRightCorner")
    floor_number: float | None = Field(default=None, alias="floorNumber")


class GetNetworkFloorPlanResponse(_BaseSchema):
    """Find a floor plan by ID."""

    floor_plan_id: str | None = Field(default=None, alias="floorPlanId")
    image_url: str | None = Field(default=None, alias="imageUrl")
    image_url_expires_at: str | None = Field(default=None, alias="imageUrlExpiresAt")
    image_extension: str | None = Field(default=None, alias="imageExtension")
    image_md5: str | None = Field(default=None, alias="imageMd5")
    name: str | None = None
    devices: list[NetworksDevicesItem2] | None = None
    width: float | None = None
    height: float | None = None
    center: NetworksCenter | None = None
    bottom_left_corner: NetworksCenter | None = Field(default=None, alias="bottomLeftCorner")
    bottom_right_corner: NetworksCenter | None = Field(default=None, alias="bottomRightCorner")
    top_left_corner: NetworksCenter | None = Field(default=None, alias="topLeftCorner")
    top_right_corner: NetworksCenter | None = Field(default=None, alias="topRightCorner")
    floor_number: float | None = Field(default=None, alias="floorNumber")


class UpdateNetworkFloorPlanResponse(_BaseSchema):
    """Update a floor plan's geolocation and other meta data."""

    floor_plan_id: str | None = Field(default=None, alias="floorPlanId")
    image_url: str | None = Field(default=None, alias="imageUrl")
    image_url_expires_at: str | None = Field(default=None, alias="imageUrlExpiresAt")
    image_extension: str | None = Field(default=None, alias="imageExtension")
    image_md5: str | None = Field(default=None, alias="imageMd5")
    name: str | None = None
    devices: list[NetworksDevicesItem2] | None = None
    width: float | None = None
    height: float | None = None
    center: NetworksCenter | None = None
    bottom_left_corner: NetworksCenter | None = Field(default=None, alias="bottomLeftCorner")
    bottom_right_corner: NetworksCenter | None = Field(default=None, alias="bottomRightCorner")
    top_left_corner: NetworksCenter | None = Field(default=None, alias="topLeftCorner")
    top_right_corner: NetworksCenter | None = Field(default=None, alias="topRightCorner")
    floor_number: float | None = Field(default=None, alias="floorNumber")


class GetNetworkDevicesResponse(RootModel[list[GetNetworkDevicesResponseItem]]):
    """List the devices in a network."""


class GetNetworkEventsResponse(_BaseSchema):
    """List the events for the network."""

    message: str | None = None
    page_start_at: str | None = Field(default=None, alias="pageStartAt")
    page_end_at: str | None = Field(default=None, alias="pageEndAt")
    events: list[GetNetworkEventsResponseEventsItem] | None = None


class NetworksProductsWireless(_BaseSchema):
    """The network device to be updated."""

    current_version: NetworksCurrentVersion | None = Field(default=None, alias="currentVersion")
    last_upgrade: NetworksLastUpgrade | None = Field(default=None, alias="lastUpgrade")
    next_upgrade: NetworksNextUpgrade | None = Field(default=None, alias="nextUpgrade")
    is_upgrade_available: bool | None = Field(default=None, alias="isUpgradeAvailable")
    available_versions: list[NetworksCurrentVersion] | None = Field(
        default=None, alias="availableVersions"
    )
    participate_in_next_beta_release: bool | None = Field(
        default=None, alias="participateInNextBetaRelease"
    )


class NetworksProductsSwitch(_BaseSchema):
    """The Switch network to be updated."""

    next_upgrade: NetworksNextUpgrade2 | None = Field(default=None, alias="nextUpgrade")


class GetNetworkFirmwareUpgradesStagedStagesResponse(
    RootModel[list[GetNetworkFirmwareUpgradesStagedStagesResponseItem]]
):
    """Order of Staged Upgrade Groups in a network."""


class UpdateNetworkFirmwareUpgradesStagedStagesResponse(
    RootModel[list[UpdateNetworkFirmwareUpgradesStagedStagesResponseItem]]
):
    """Assign Staged Upgrade Group order in the sequence."""


class GetNetworkFirmwareUpgradesStagedGroupsResponseItem(_BaseSchema):
    """Schema for GetNetworkFirmwareUpgradesStagedGroupsResponseItem."""

    group_id: str | None = Field(default=None, alias="groupId")
    name: str | None = None
    description: str | None = None
    is_default: bool | None = Field(default=None, alias="isDefault")
    assigned_devices: NetworksAssignedDevices | None = Field(default=None, alias="assignedDevices")


class CreateNetworkFirmwareUpgradesStagedGroupResponse(_BaseSchema):
    """Create a Staged Upgrade Group for a network."""

    group_id: str | None = Field(default=None, alias="groupId")
    name: str | None = None
    description: str | None = None
    is_default: bool | None = Field(default=None, alias="isDefault")
    assigned_devices: NetworksAssignedDevices | None = Field(default=None, alias="assignedDevices")


class GetNetworkFirmwareUpgradesStagedGroupResponse(_BaseSchema):
    """Get a Staged Upgrade Group from a network."""

    group_id: str | None = Field(default=None, alias="groupId")
    name: str | None = None
    description: str | None = None
    is_default: bool | None = Field(default=None, alias="isDefault")
    assigned_devices: NetworksAssignedDevices | None = Field(default=None, alias="assignedDevices")


class UpdateNetworkFirmwareUpgradesStagedGroupResponse(_BaseSchema):
    """Update a Staged Upgrade Group for a network."""

    group_id: str | None = Field(default=None, alias="groupId")
    name: str | None = None
    description: str | None = None
    is_default: bool | None = Field(default=None, alias="isDefault")
    assigned_devices: NetworksAssignedDevices | None = Field(default=None, alias="assignedDevices")


class GetNetworkVlanProfilesResponseItem(_BaseSchema):
    """Schema for GetNetworkVlanProfilesResponseItem."""

    iname: str | None = None
    name: str | None = None
    is_default: bool | None = Field(default=None, alias="isDefault")
    vlan_names: list[NetworksVlanNamesItem] | None = Field(default=None, alias="vlanNames")
    vlan_groups: list[NetworksVlanGroupsItem] | None = Field(default=None, alias="vlanGroups")


class CreateNetworkVlanProfileResponse(_BaseSchema):
    """Create a VLAN profile for a network."""

    iname: str | None = None
    name: str | None = None
    is_default: bool | None = Field(default=None, alias="isDefault")
    vlan_names: list[NetworksVlanNamesItem] | None = Field(default=None, alias="vlanNames")
    vlan_groups: list[NetworksVlanGroupsItem] | None = Field(default=None, alias="vlanGroups")


class GetNetworkVlanProfileResponse(_BaseSchema):
    """Get an existing VLAN profile of a network."""

    iname: str | None = None
    name: str | None = None
    is_default: bool | None = Field(default=None, alias="isDefault")
    vlan_names: list[NetworksVlanNamesItem] | None = Field(default=None, alias="vlanNames")
    vlan_groups: list[NetworksVlanGroupsItem] | None = Field(default=None, alias="vlanGroups")


class UpdateNetworkVlanProfileResponse(_BaseSchema):
    """Update an existing VLAN profile of a network."""

    iname: str | None = None
    name: str | None = None
    is_default: bool | None = Field(default=None, alias="isDefault")
    vlan_names: list[NetworksVlanNamesItem] | None = Field(default=None, alias="vlanNames")
    vlan_groups: list[NetworksVlanGroupsItem] | None = Field(default=None, alias="vlanGroups")


class BatchNetworkFloorPlansAutoLocateJobsResponseJobsItem(_BaseSchema):
    """Schema for BatchNetworkFloorPlansAutoLocateJobsResponseJobsItem."""

    id_: str | None = Field(default=None, alias="id")
    network_id: str | None = Field(default=None, alias="networkId")
    floor_plan_id: str | None = Field(default=None, alias="floorPlanId")
    status: str | None = None
    scheduled_at: str | None = Field(default=None, alias="scheduledAt")
    completed: NetworksJobsCompleted | None = None
    ranging: NetworksJobsRanging | None = None
    gnss: NetworksJobsRanging | None = None
    errors: list[NetworksJobsErrorsItem] | None = None


class NetworksPerClientBandwidthLimits(_BaseSchema):
    """An object describing the bandwidth settings for your rule."""

    settings: str | None = None
    bandwidth_limits: NetworksBandwidthLimits | None = Field(default=None, alias="bandwidthLimits")


class NetworksScope(_BaseSchema):
    """The scope of the alert."""

    devices: list[NetworksDevicesItem3] | None = None
    applications: list[NetworksApplicationsItem] | None = None
    peers: list[NetworksPeersItem] | None = None


class GetNetworkMerakiAuthUsersResponse(RootModel[list[GetNetworkMerakiAuthUsersResponseItem]]):
    """List the authorized users configured under Meraki Authentication for a network (splash guest
    or RADIUS users for a wireless network, or client VPN users for a MX network).
    """


class GetNetworkMqttBrokersResponseItem(_BaseSchema):
    """Schema for GetNetworkMqttBrokersResponseItem."""

    id_: str | None = Field(default=None, alias="id")
    name: str | None = None
    host: str | None = None
    port: int | None = None
    security: NetworksSecurity | None = None
    authentication: NetworksAuthentication | None = None


class CreateNetworkMqttBrokerResponse(_BaseSchema):
    """Add an MQTT broker."""

    id_: str | None = Field(default=None, alias="id")
    name: str | None = None
    host: str | None = None
    port: int | None = None
    security: NetworksSecurity | None = None
    authentication: NetworksAuthentication | None = None


class GetNetworkMqttBrokerResponse(_BaseSchema):
    """Return an MQTT broker."""

    id_: str | None = Field(default=None, alias="id")
    name: str | None = None
    host: str | None = None
    port: int | None = None
    security: NetworksSecurity | None = None
    authentication: NetworksAuthentication | None = None


class UpdateNetworkMqttBrokerResponse(_BaseSchema):
    """Update an MQTT broker."""

    id_: str | None = Field(default=None, alias="id")
    name: str | None = None
    host: str | None = None
    port: int | None = None
    security: NetworksSecurity | None = None
    authentication: NetworksAuthentication | None = None


class GetNetworkNetworkHealthChannelUtilizationResponse(
    RootModel[list[GetNetworkNetworkHealthChannelUtilizationResponseItem]]
):
    """Get the channel utilization over each radio for all APs in a network."""


class GetNetworkPoliciesByClientResponseItem(_BaseSchema):
    """Schema for GetNetworkPoliciesByClientResponseItem."""

    name: str | None = None
    client_id: str | None = Field(default=None, alias="clientId")
    assigned: list[NetworksAssignedItem] | None = None


class GetNetworkSettingsResponse(_BaseSchema):
    """Return the settings for a network."""

    local_status_page_enabled: bool | None = Field(default=None, alias="localStatusPageEnabled")
    remote_status_page_enabled: bool | None = Field(default=None, alias="remoteStatusPageEnabled")
    local_status_page: GetNetworkSettingsResponseLocalStatusPage | None = Field(
        default=None, alias="localStatusPage"
    )
    secure_port: NetworksMutingByPortSchedules | None = Field(default=None, alias="securePort")
    fips: NetworksMutingByPortSchedules | None = None
    named_vlans: GetNetworkSettingsResponseNamedVlans | None = Field(
        default=None, alias="namedVlans"
    )


class NetworksNodesDevice(_BaseSchema):
    """Device information (present when type is 'device')."""

    serial: str | None = None
    name: str | None = None
    model: str | None = None
    product_type: str | None = Field(default=None, alias="productType")
    status: str | None = None
    last_reported_at: str | None = Field(default=None, alias="lastReportedAt")
    clients: NetworksClients | None = None
    uplinks: list[NetworksUplinksItem] | None = None


class NetworksNodesStack(_BaseSchema):
    """Stack information (present when type is 'stack')."""

    id_: int | None = Field(default=None, alias="id")
    name: str | None = None
    members: list[dict[str, Any]] | None = None
    clients: NetworksClients | None = None


class NetworksLinksEndsItem(_BaseSchema):
    """Schema for NetworksLinksEndsItem."""

    node: NetworksNode | None = None
    device: NetworksDevicesItem | None = None
    discovered: NetworksDiscovered | None = None


class GetNetworkVlanProfilesAssignmentsByDeviceResponse(
    RootModel[list[GetNetworkVlanProfilesAssignmentsByDeviceResponseItem]]
):
    """Get the assigned VLAN Profiles for devices in a network."""


class GetNetworkWebhooksHttpServersResponse(
    RootModel[list[GetNetworkWebhooksHttpServersResponseItem]]
):
    """List the HTTP servers for a network."""


class GetNetworkWebhooksPayloadTemplatesResponseItem(_BaseSchema):
    """Schema for GetNetworkWebhooksPayloadTemplatesResponseItem."""

    payload_template_id: str | None = Field(default=None, alias="payloadTemplateId")
    type_: str | None = Field(default=None, alias="type")
    name: str | None = None
    headers: list[NetworksHeadersItem] | None = None
    body: str | None = None
    sharing: NetworksSharing | None = None


class CreateNetworkWebhooksPayloadTemplateResponse(_BaseSchema):
    """Create a webhook payload template for a network."""

    payload_template_id: str | None = Field(default=None, alias="payloadTemplateId")
    type_: str | None = Field(default=None, alias="type")
    name: str | None = None
    headers: list[NetworksHeadersItem] | None = None
    body: str | None = None
    sharing: NetworksSharing | None = None


class GetNetworkWebhooksPayloadTemplateResponse(_BaseSchema):
    """Get the webhook payload template for a network."""

    payload_template_id: str | None = Field(default=None, alias="payloadTemplateId")
    type_: str | None = Field(default=None, alias="type")
    name: str | None = None
    headers: list[NetworksHeadersItem] | None = None
    body: str | None = None
    sharing: NetworksSharing | None = None


class UpdateNetworkWebhooksPayloadTemplateResponse(_BaseSchema):
    """Update a webhook payload template for a network."""

    payload_template_id: str | None = Field(default=None, alias="payloadTemplateId")
    type_: str | None = Field(default=None, alias="type")
    name: str | None = None
    headers: list[NetworksHeadersItem] | None = None
    body: str | None = None
    sharing: NetworksSharing | None = None


class GetNetworkAlertsHistoryResponse(RootModel[list[GetNetworkAlertsHistoryResponseItem]]):
    """Return the alert history for this network."""


class GetNetworkAlertsSettingsResponse(_BaseSchema):
    """Return the alert configuration for this network."""

    default_destinations: GetNetworkAlertsSettingsResponseDefaultDestinations | None = Field(
        default=None, alias="defaultDestinations"
    )
    alerts: list[GetNetworkAlertsSettingsResponseAlertsItem] | None = None
    muting: GetNetworkAlertsSettingsResponseMuting | None = None


class GetNetworkFloorPlansResponse(RootModel[list[GetNetworkFloorPlansResponseItem]]):
    """List the floor plans that belong to your network."""


class GetNetworkFirmwareUpgradesResponseProducts(_BaseSchema):
    """The network devices to be updated."""

    wireless: NetworksProductsWireless | None = None
    appliance: NetworksProductsWireless | None = None
    switch: NetworksProductsWireless | None = None
    camera: NetworksProductsWireless | None = None
    cellular_gateway: NetworksProductsWireless | None = Field(default=None, alias="cellularGateway")
    sensor: NetworksProductsWireless | None = None
    wireless_controller: NetworksProductsWireless | None = Field(
        default=None, alias="wirelessController"
    )
    secure_connect: NetworksProductsWireless | None = Field(default=None, alias="secureConnect")


class GetNetworkFirmwareUpgradesStagedEventsResponseProducts(_BaseSchema):
    """The network devices to be updated."""

    switch: NetworksProductsSwitch | None = None


class GetNetworkFirmwareUpgradesStagedGroupsResponse(
    RootModel[list[GetNetworkFirmwareUpgradesStagedGroupsResponseItem]]
):
    """List of Staged Upgrade Groups in a network."""


class GetNetworkVlanProfilesResponse(RootModel[list[GetNetworkVlanProfilesResponseItem]]):
    """List VLAN profiles for a network."""


class BatchNetworkFloorPlansAutoLocateJobsResponse(_BaseSchema):
    """Schedule auto locate jobs for one or more floor plans in a network."""

    jobs: list[BatchNetworkFloorPlansAutoLocateJobsResponseJobsItem] | None = None


class NetworksTrafficShapingRulesItem(_BaseSchema):
    """Schema for NetworksTrafficShapingRulesItem."""

    definitions: list[NetworksDefinitionsItem]
    per_client_bandwidth_limits: NetworksPerClientBandwidthLimits | None = Field(
        default=None, alias="perClientBandwidthLimits"
    )
    dscp_tag_value: int | None = Field(default=None, alias="dscpTagValue")
    pcp_tag_value: int | None = Field(default=None, alias="pcpTagValue")
    priority: str | None = None


class GetNetworkHealthAlertsResponseItem(_BaseSchema):
    """Schema for GetNetworkHealthAlertsResponseItem."""

    id_: str | None = Field(default=None, alias="id")
    category: str | None = None
    type_: str | None = Field(default=None, alias="type")
    severity: str | None = None
    scope: NetworksScope | None = None


class GetNetworkMqttBrokersResponse(RootModel[list[GetNetworkMqttBrokersResponseItem]]):
    """List the MQTT brokers for this network."""


class GetNetworkPoliciesByClientResponse(RootModel[list[GetNetworkPoliciesByClientResponseItem]]):
    """Get policies for all clients with policies."""


class UpdateNetworkSettingsResponse(_BaseSchema):
    """Update the settings for a network."""

    local_status_page_enabled: bool | None = Field(default=None, alias="localStatusPageEnabled")
    remote_status_page_enabled: bool | None = Field(default=None, alias="remoteStatusPageEnabled")
    local_status_page: GetNetworkSettingsResponseLocalStatusPage | None = Field(
        default=None, alias="localStatusPage"
    )
    secure_port: NetworksMutingByPortSchedules | None = Field(default=None, alias="securePort")
    fips: NetworksMutingByPortSchedules | None = None
    named_vlans: GetNetworkSettingsResponseNamedVlans | None = Field(
        default=None, alias="namedVlans"
    )


class GetNetworkTopologyLinkLayerResponseNodesItem(_BaseSchema):
    """Schema for GetNetworkTopologyLinkLayerResponseNodesItem."""

    derived_id: str | None = Field(default=None, alias="derivedId")
    mac: str | None = None
    type_: str | None = Field(default=None, alias="type")
    root: bool | None = None
    device: NetworksNodesDevice | None = None
    discovered: NetworksNodesDiscovered | None = None
    stack: NetworksNodesStack | None = None


class GetNetworkTopologyLinkLayerResponseLinksItem(_BaseSchema):
    """Schema for GetNetworkTopologyLinkLayerResponseLinksItem."""

    ends: list[NetworksLinksEndsItem] | None = None
    last_reported_at: str | None = Field(default=None, alias="lastReportedAt")


class GetNetworkWebhooksPayloadTemplatesResponse(
    RootModel[list[GetNetworkWebhooksPayloadTemplatesResponseItem]]
):
    """List the webhook payload templates for a network."""


class UpdateNetworkAlertsSettingsResponse(_BaseSchema):
    """Update the alert configuration for this network."""

    default_destinations: GetNetworkAlertsSettingsResponseDefaultDestinations | None = Field(
        default=None, alias="defaultDestinations"
    )
    alerts: list[GetNetworkAlertsSettingsResponseAlertsItem] | None = None
    muting: GetNetworkAlertsSettingsResponseMuting | None = None


class GetNetworkFirmwareUpgradesResponse(_BaseSchema):
    """Get firmware upgrade information for a network."""

    upgrade_window: GetNetworkFirmwareUpgradesResponseUpgradeWindow | None = Field(
        default=None, alias="upgradeWindow"
    )
    timezone: str | None = None
    products: GetNetworkFirmwareUpgradesResponseProducts | None = None


class GetNetworkFirmwareUpgradesStagedEventsResponse(_BaseSchema):
    """Get the Staged Upgrade Event from a network."""

    products: GetNetworkFirmwareUpgradesStagedEventsResponseProducts | None = None
    stages: list[GetNetworkFirmwareUpgradesStagedEventsResponseStagesItem] | None = None
    reasons: list[CreateNetworkFirmwareUpgradesRollbackResponseReasonsItem] | None = None


class NetworksFirewallAndTrafficShaping(_BaseSchema):
    """The firewall and traffic shaping rules and settings for your policy."""

    settings: str | None = None
    traffic_shaping_rules: list[NetworksTrafficShapingRulesItem] | None = Field(
        default=None, alias="trafficShapingRules"
    )
    l3_firewall_rules: list[NetworksL3FirewallRulesItem] | None = Field(
        default=None, alias="l3FirewallRules"
    )
    l7_firewall_rules: list[NetworksL7FirewallRulesItem] | None = Field(
        default=None, alias="l7FirewallRules"
    )


class GetNetworkHealthAlertsResponse(RootModel[list[GetNetworkHealthAlertsResponseItem]]):
    """Return all global alerts on this network."""


class GetNetworkTopologyLinkLayerResponse(_BaseSchema):
    """List the LLDP and CDP information for all discovered devices and connections in a network.
    At least one MX or MS device must be in the network in order to build the topology.
    """

    nodes: list[GetNetworkTopologyLinkLayerResponseNodesItem] | None = None
    links: list[GetNetworkTopologyLinkLayerResponseLinksItem] | None = None
    errors: list[str] | None = None


class UpdateNetworkFirmwareUpgradesResponse(_BaseSchema):
    """Update firmware upgrade information for a network."""

    upgrade_window: GetNetworkFirmwareUpgradesResponseUpgradeWindow | None = Field(
        default=None, alias="upgradeWindow"
    )
    timezone: str | None = None
    products: GetNetworkFirmwareUpgradesResponseProducts | None = None


class UpdateNetworkFirmwareUpgradesStagedEventsResponse(_BaseSchema):
    """Update the Staged Upgrade Event for a network."""

    products: GetNetworkFirmwareUpgradesStagedEventsResponseProducts | None = None
    stages: list[GetNetworkFirmwareUpgradesStagedEventsResponseStagesItem] | None = None
    reasons: list[CreateNetworkFirmwareUpgradesRollbackResponseReasonsItem] | None = None


class CreateNetworkFirmwareUpgradesStagedEventResponse(_BaseSchema):
    """Create a Staged Upgrade Event for a network."""

    products: GetNetworkFirmwareUpgradesStagedEventsResponseProducts | None = None
    stages: list[GetNetworkFirmwareUpgradesStagedEventsResponseStagesItem] | None = None
    reasons: list[CreateNetworkFirmwareUpgradesRollbackResponseReasonsItem] | None = None


class DeferNetworkFirmwareUpgradesStagedEventsResponse(_BaseSchema):
    """Postpone by 1 week all pending staged upgrade stages for a network."""

    products: GetNetworkFirmwareUpgradesStagedEventsResponseProducts | None = None
    stages: list[GetNetworkFirmwareUpgradesStagedEventsResponseStagesItem] | None = None
    reasons: list[CreateNetworkFirmwareUpgradesRollbackResponseReasonsItem] | None = None


class RollbacksNetworkFirmwareUpgradesStagedEventsResponse(_BaseSchema):
    """Rollback a Staged Upgrade Event for a network."""

    products: GetNetworkFirmwareUpgradesStagedEventsResponseProducts | None = None
    stages: list[GetNetworkFirmwareUpgradesStagedEventsResponseStagesItem] | None = None
    reasons: list[CreateNetworkFirmwareUpgradesRollbackResponseReasonsItem] | None = None


class GetNetworkGroupPoliciesResponseItem(_BaseSchema):
    """Schema for GetNetworkGroupPoliciesResponseItem."""

    group_policy_id: str | None = Field(default=None, alias="groupPolicyId")
    scheduling: NetworksScheduling | None = None
    bandwidth: NetworksBandwidth | None = None
    firewall_and_traffic_shaping: NetworksFirewallAndTrafficShaping | None = Field(
        default=None, alias="firewallAndTrafficShaping"
    )
    content_filtering: NetworksContentFiltering | None = Field(
        default=None, alias="contentFiltering"
    )
    splash_auth_settings: str | None = Field(default=None, alias="splashAuthSettings")
    vlan_tagging: NetworksVlanTagging | None = Field(default=None, alias="vlanTagging")
    bonjour_forwarding: NetworksBonjourForwarding | None = Field(
        default=None, alias="bonjourForwarding"
    )


class CreateNetworkGroupPolicyResponse(_BaseSchema):
    """Create a group policy."""

    group_policy_id: str | None = Field(default=None, alias="groupPolicyId")
    scheduling: NetworksScheduling | None = None
    bandwidth: NetworksBandwidth | None = None
    firewall_and_traffic_shaping: NetworksFirewallAndTrafficShaping | None = Field(
        default=None, alias="firewallAndTrafficShaping"
    )
    content_filtering: NetworksContentFiltering | None = Field(
        default=None, alias="contentFiltering"
    )
    splash_auth_settings: str | None = Field(default=None, alias="splashAuthSettings")
    vlan_tagging: NetworksVlanTagging | None = Field(default=None, alias="vlanTagging")
    bonjour_forwarding: NetworksBonjourForwarding | None = Field(
        default=None, alias="bonjourForwarding"
    )


class GetNetworkGroupPolicyResponse(_BaseSchema):
    """Display a group policy."""

    group_policy_id: str | None = Field(default=None, alias="groupPolicyId")
    scheduling: NetworksScheduling | None = None
    bandwidth: NetworksBandwidth | None = None
    firewall_and_traffic_shaping: NetworksFirewallAndTrafficShaping | None = Field(
        default=None, alias="firewallAndTrafficShaping"
    )
    content_filtering: NetworksContentFiltering | None = Field(
        default=None, alias="contentFiltering"
    )
    splash_auth_settings: str | None = Field(default=None, alias="splashAuthSettings")
    vlan_tagging: NetworksVlanTagging | None = Field(default=None, alias="vlanTagging")
    bonjour_forwarding: NetworksBonjourForwarding | None = Field(
        default=None, alias="bonjourForwarding"
    )


class UpdateNetworkGroupPolicyResponse(_BaseSchema):
    """Update a group policy."""

    group_policy_id: str | None = Field(default=None, alias="groupPolicyId")
    scheduling: NetworksScheduling | None = None
    bandwidth: NetworksBandwidth | None = None
    firewall_and_traffic_shaping: NetworksFirewallAndTrafficShaping | None = Field(
        default=None, alias="firewallAndTrafficShaping"
    )
    content_filtering: NetworksContentFiltering | None = Field(
        default=None, alias="contentFiltering"
    )
    splash_auth_settings: str | None = Field(default=None, alias="splashAuthSettings")
    vlan_tagging: NetworksVlanTagging | None = Field(default=None, alias="vlanTagging")
    bonjour_forwarding: NetworksBonjourForwarding | None = Field(
        default=None, alias="bonjourForwarding"
    )


class GetNetworkGroupPoliciesResponse(RootModel[list[GetNetworkGroupPoliciesResponseItem]]):
    """List the group policies in a network."""
